### ISSUE TITLE
Ambiguous docs

### ISSUE THREAD

**Issue by andybak** [KozGit/DOOM-3-BFG-VR#10]
The following paragraph:  "The combined scipts directory is now included in the install zip as 'all_in_one_script'. Rename the directory 'all_in_one_script' to 'script' and launch the mod."

might either belong to "if you are using the texture pack" or it might be separate and therefore relevant to both "using" and "not using" the texture pack.

Could you fix the formatting so it's clearer which is the case?

**Comment by KozGit** [comment]
Will fix.  If you are not using the hidef texture pack, you do not need to delete/rename the script directory.

**Comment by KozGit** [comment]
Directions changed to:

If you are NOT using the texture pack, extract the mod files at this time and run the exe to play. See readme_install.txt inside the archive for additional info.

If you ARE using the texture pack:
Re-install the texture pack at this point, then extract the mod archive as before.
DELETE the 'SCRIPTS' directory. The combined scipts directory is now included in the install zip as 'all_in_one_script'. Rename the directory 'all_in_one_script' to 'script' and launch the mod.
