### ISSUE TITLE
Vive controls unresponsive.

### ISSUE THREAD

**Issue by Bind777** [KozGit/DOOM-3-BFG-VR#106]
Just installed it and when I first booted up the game it worked fine. I had to change the language so I exited and deleted the german text file, went back in and the controls no longer work. Tried a fresh install of BFG and it did not resolve.

Edit: Did a complete wipe of the game and still nothing. Also tried it again with the german language file and it wont return to working.

**Comment by teppotee** [comment]
Having the same issue. Started the game for the first time with the german.lang file still in the folder and the controllers were working fine. Noticed the german language in the menu --> exited game, deleted the file and after restarting the game the vive controls don't work even in the menus anymore.  In the game I can see the hands and they are tracking fine. However none of the buttons work (except SteamVR menu button). Haven't been able to fix it.

**Comment by CarlKenner** [comment]
Try going to the folder %UserProfile%\Saved Games\id Software\DOOM 3 BFG\Fully Possessed
and deleting vr_oculus.cfg and vr_openvr.cfg

**Comment by Bind777** [comment]
@CarlKenner That did it. Cheers, mate.

**Comment by CarlKenner** [comment]
Don't close it. Now nobody else can see what to do. I can't reopen issues (only Samson can).

**Comment by Bind777** [comment]
@CarlKenner Apologies. Wasn't aware.

**Comment by TerratoWorzen** [comment]
Hello. Just installed it and before I ran it for the first time I deleted the German file. Arms are tracking fine too, but can't do anything else at all, not even navigate menus.
Is there anyway to fix this?
Thanks in advance.

**Comment by calcanuck** [comment]
My Vive controller problems were solved by unplugging my XBox controller.
