### ISSUE TITLE
Locomotion controlled by opposite hand

### ISSUE THREAD

**Issue by damonlazer** [KozGit/DOOM-3-BFG-VR#107]
I tried playing the game with the left hand selected as my main weapon hand, but the locomotion is very disorienting in this mode.  The direction of movement is determined by the right controller, but the speed/toggle of movement itself is controlled by pressing the left thumb pad.  Is there a way to configure the controls so that the velocity controlled by a single controller rather than two?

**Comment by CarlKenner** [comment]
There's no option for "weapon-hand = forward" yet.

The obvious fix is to set the right thumb pad to control movement and the left thumb pad to control the other stuff. The easiest way to do that is to go back to the menu and change the weapon hand back to your right hand. The use the console to set:
`vr_handSwapsAnalogs` 1
Then change the weapon hand to your left hand. That will swap the analogs too. 

Your only other option is to change the movement mode to "Look = forward" or "Standard Stick Move". But that's not really what you want.

**Comment by CarlKenner** [comment]
This is now fixed in the next version.

**Comment by damonlazer** [comment]
Thank you!  In the meantime, the console command works fine.
