### ISSUE TITLE
UI options

### ISSUE THREAD

**Issue by tkapis** [KozGit/DOOM-3-BFG-VR#108]
In the UI options in settings the HUD and PDA options are empty.

**Comment by CarlKenner** [comment]
Did you try clicking on them?

**Comment by tkapis** [comment]
I'm using touch and when touching them I hear a sound but nothing happens.

**Comment by Andenlol** [comment]
Yeah I can't press on them either with my hand. But if you use the trigger on the controller it works.

**Comment by CarlKenner** [comment]
I can confirm this is a bug when using touchscreen controls.

**Comment by CarlKenner** [comment]
Fixed.
