### ISSUE TITLE
Crashing on loading game

### ISSUE THREAD

**Issue by tkapis** [KozGit/DOOM-3-BFG-VR#109]
I saved at the top of the stairs by the exit of Mars Underground and after the marine talking to me I saved again. The 1st save still works but when loading the 2nd one, the game crashes. In fact any save from then on crashes if I try to load it.

**Comment by CarlKenner** [comment]
This is a duplicate of issue #103 crash when loading savegame.

**Comment by KozGit** [comment]
Closing issue,  crashing from loading saves from the same version has been addressed per above,
