### ISSUE TITLE
My controls have become unmapped

### ISSUE THREAD

**Issue by andybak** [KozGit/DOOM-3-BFG-VR#11]
Not sure how. Menus work fine but no controls on the Vive wands work. Other than remapping everything by hand - is there a quick fix?

**Comment by KozGit** [comment]
Are the controls unmapped, or just not responding?  If somehow they came unmapped, from the console ( press~ to open console ) type exec vr_default.cfg and it will restore the default controller bindings.

**Comment by andybak** [comment]
Oddly it seemed to fix itself.
