### ISSUE TITLE
slight stutter every 2 secs

### ISSUE THREAD

**Issue by masher42** [KozGit/DOOM-3-BFG-VR#113]
I am playing using full dpad locomotion and i can clearly see a slight stutter roughly every two seconds. I don't notice it when just standing there and looking around. You can notice it best when strafing along a wall while looking at it.

I played another VR mod for doom3 bfg on my vive and it doesn't stutter at all ([https://github.com/Codes4Fun/RBDOOM-3-BFG](url)) . So, i don't believe it's my hardware causing the stutters (I7 4790K, 32GB DDR3, GTX1070, Win10).

**Comment by CarlKenner** [comment]
I think I know what's causing that. It's a timing issue.
Try com_fixedTic 1 in the console.

**Comment by masher42** [comment]
Brilliant ! That was causing it. Now it's silky smooth. Problem solved :) I think i remember having to do this to the regular non bfg edition of doom3 to get it to be 100% smooth.

**Comment by KozGit** [comment]
Closing issue, addressed in updates.
