### ISSUE TITLE
Player height is not saved between session or level loads.

### ISSUE THREAD

**Issue by CylonSurfer** [KozGit/DOOM-3-BFG-VR#115]
Changing the following option is not saved between sessions or level loads:

VR Character Settings > View Height

It is set to 68 as default and if I lower it to say 66, upon loading the game or the game loading after a cutscene or loading the next level it is returned to 68. 

I also notice that the Oculus Guardian boundaries are also hovering above the ingame floor height, and that I cannot reach the floor if I crouch and try to touch it. Maybe this has an impact on why my character seems to tall in game and I need to keep lowering the view height.

**Comment by KozGit** [comment]
I see were this is not being saved - whoops!

The game character is about 76 inches tall, and I left that as the default height.  If you are shorter than that ( I'm not that tall myself ),  but want to play a 6'4" marine in the game, there is no way for the chaperone/guardian to line up with the floor.  

Changing the view height is the right way to address this, sorry it's not saving.

I'm working on adding some world scale options, will address this with those options soon.

**Comment by CylonSurfer** [comment]
Cheers & no rush - its just a minor annoyance! 
Great work on the last release BTW.
