### ISSUE TITLE
Closing the menu in game crashes game

### ISSUE THREAD

**Issue by rogerperez** [KozGit/DOOM-3-BFG-VR#116]
Using the HTC Vive, when I close the menu in game, the game crashes.

**Comment by CarlKenner** [comment]
What graphics card do you have?
What mods/texture packs are you using?

**Comment by rogerperez** [comment]
I have a GTX-1070 and this issue has happened both with the vanilla install and with the "Texture/Ultimate HD compiled by Wildside VR" pack.

**Comment by rogerperez** [comment]
Got this from the Windows Event Viewer
`The application-specific permission settings do not grant Local Activation permission for the COM Server application with CLSID 
{D63B10C5-BB46-4990-A94F-E40B9D520160}
 and APPID 
{9CA88EE3-ACB7-47C8-AFC4-AB702511C276}
 to the user NT AUTHORITY\SYSTEM SID (S-1-5-18) from address LocalHost (Using LRPC) running in the application container Unavailable SID (Unavailable). This security permission can be modified using the Component Services administrative tool.`

**Comment by KozGit** [comment]
Check this link and see if it helps.

https://shauncassells.wordpress.com/2015/09/28/windows-10-event-10016-fix-the-application-specific-permission-settings-do-not-grant-local-activation-permission-for-the-com-server-application-with-clsid-d63b10c5-bb46-4990-a94f-e40b9d520160-and-a/

**Comment by KozGit** [comment]
There hasn't been an update to this in a while, and no response to the above suggestion, and no further reports of this issue.  I'm closing the issue, feel free to reopen if the issue persists.

Thx!
