### ISSUE TITLE
Can't install the plugin

### ISSUE THREAD

**Issue by oodarkriseoo** [KozGit/DOOM-3-BFG-VR#117]
When i execute the Doom3BFGVR_Fully_Possessed_Alpha020.exe , windows says me that this application cannot be executed on my computer and that I have to find the right version for my computer whereas i'am under Win 10 64bit with a GTX970 graph card. I don't understand...

**Comment by CarlKenner** [comment]
Maybe it didn't download properly?
If you can't get the installer to work, you can just use the zip file.

**Comment by KozGit** [comment]
Closing as no response in 3 days, if the issue persists please reopen.
