### ISSUE TITLE
deactivated weapon change on trackpad HTC

### ISSUE THREAD

**Issue by bysty666** [KozGit/DOOM-3-BFG-VR#118]
Hello i use teleport version and i like it very much !  thanks for this amazing work KozGIt, but i have a problem when i use teleport, the weapon change automatically and very often i m on monster... with just my hands ...   :/   it is possible to desactivate weapon change on left trackpad ? 

Thanks !!!

**Comment by CarlKenner** [comment]
You can change any of the control bindings in the menu (the Controls menu, not the VR Options menu).

By the way, I made a new version:
https://github.com/KozGit/DOOM-3-BFG-VR/pull/110

**Comment by bysty666** [comment]
^^ thank you, but i can put new command but not delete ancient command.

**Comment by bysty666** [comment]
May be i can change it in vr_openvr_default.cfg ?

because i always have the same problem

**Comment by KozGit** [comment]
To unbind a control, in settings->controls->key bindings, select the action you want to unbind, go into bind mode, then press the button/pad/joystick/key/whatever it is you want to unbind, and it will unbind it. ( You use the exact same process to bind or unbind a control ) 

There was also an issue in the older version where voice commands could recognize sounds from the game or breath sounds as 'fist' and switch weapons.  Try disabling voice commands if the issue persists.

**Comment by KozGit** [comment]
No further updates, closing issue.  Please note that it was most likely the voice commands causing the unintended weapon switch.
