### ISSUE TITLE
crash on activating first elevator/ alpha 021

### ISSUE THREAD

**Issue by juicyjester** [KozGit/DOOM-3-BFG-VR#122]
using alpha 021, the game crashes on a fresh game play on the first mission (locate the engineer i think it was, cos your a fng lol) when you enter the elevator and press the button. while loading it just crashes. sorry new here if that wasnt enough info

**Comment by KozGit** [comment]
Do you have the texture pack installed?  Any info you can post from the crash?

**Comment by KozGit** [comment]
Can't duplicate the issue, and no further info, so closing this issue. If it persists, please open a new issue and provide as much of no as possible, thanks.
