### ISSUE TITLE
Crash on start up

### ISSUE THREAD

**Issue by Astamurti** [KozGit/DOOM-3-BFG-VR#123]
When I try to start the VR, I get the following error:

WARNING: CVar 'developer' declared multiple times with different initial value
QA Timing INIT: 000011ms
DOOM 3 BFG VR 1.0.3.1401 win-x86 Mar  9 2017 18:56:27
4008 MHz Intel CPU with MMX & SSE & SSE2 & SSE3 & HTT
Winsock Initialized
Found interface: {48D93D1E-40B0-4CAB-8B89-244EC4BA4C31} Intel(R) Ethernet Connection (2) I219-V - 0.0.0.0 NULL netmask - skipped
Found interface: {2F9158F2-EDA1-4AD5-B973-FAB1D473BFAF} Dell Wireless 1560 802.11ac - 192.168.1.9/255.255.255.0
Found interface: {47F62497-9492-4982-865A-E6874CB77E1F} Microsoft Wi-Fi Direct Virtual Adapter - 0.0.0.0 NULL netmask - skipped
Found interface: {FAF6DD0D-A7EF-440D-8ACA-757FDDF010E4} Microsoft Wi-Fi Direct Virtual Adapter #2 - 0.0.0.0 NULL netmask - skipped
Sys_InitNetworking: adding loopback interface
doom using MMX & SSE for SIMD processing
enabled Flush-To-Zero mode
enabled Denormals-Are-Zero mode
------ Initializing File System ------
Current search path:
C:\Users\GuestLogIn\Saved Games\id Software\DOOM 3 BFG/Fully Possessed
c:\program files (x86)\steam\steamapps\common\DOOM 3 BFG Edition/Fully Possessed
C:\Users\GuestLogIn\Saved Games\id Software\DOOM 3 BFG/base
c:\program files (x86)\steam\steamapps\common\DOOM 3 BFG Edition/base
file system initialized.
--------------------------------------
Unknown command 'vid_restart'
Couldn't load default.cfg
Shutting down OpenGL subsystem
...wglMakeCurrent( NULL, NULL ): failed

-----------------------------------------------------------------------------------------------------

I attempted to resolve this issue by renaming the vr_openvr_default.cfg to just default.cfg. This allowed the start-up process to advance slightly further, generating the initial window but then crashing anyway with the new error:

writing to: C:\Users\GuestLogIn\Saved Games\id Software\DOOM 3 BFG\Fully Possessed\renderprogs\hlsl\blendlight_fragment.hlsl
writing to: C:\Users\GuestLogIn\Saved Games\id Software\DOOM 3 BFG\Fully Possessed\renderprogs\glsl-1_50\blendlight_fragment.glsl
writing to: C:\Users\GuestLogIn\Saved Games\id Software\DOOM 3 BFG\Fully Possessed\renderprogs\glsl-1_50\blendlight_fragment.uniforms
writing to: C:\Users\GuestLogIn\Saved Games\id Software\DOOM 3 BFG\Fully Possessed\renderprogs\hlsl\fog_vertex.hlsl
writing to: C:\Users\GuestLogIn\Saved Games\id Software\DOOM 3 BFG\Fully Possessed\renderprogs\glsl-1_50\fog_vertex.glsl
writing to: C:\Users\GuestLogIn\Saved Games\id Software\DOOM 3 BFG\Fully Possessed\renderprogs\glsl-1_50\fog_vertex.uniforms
writing to: C:\Users\GuestLogIn\Saved Games\id Software\DOOM 3 BFG\Fully Possessed\renderprogs\hlsl\fog_fragment.hlsl
writing to: C:\Users\GuestLogIn\Saved Games\id Software\DOOM 3 BFG\Fully Possessed\renderprogs\glsl-1_50\fog_fragment.glsl
writing to: C:\Users\GuestLogIn\Saved Games\id Software\DOOM 3 BFG\Fully Possessed\renderprogs\glsl-1_50\fog_fragment.uniforms
writing to: C:\Users\GuestLogIn\Saved Games\id Software\DOOM 3 BFG\Fully Possessed\renderprogs\hlsl\fog_skinned_vertex.hlsl
writing to: C:\Users\GuestLogIn\Saved Games\id Software\DOOM 3 BFG\Fully Possessed\renderprogs\glsl-1_50\fog_skinned_vertex.glsl
writing to: C:\Users\GuestLogIn\Saved Games\id Software\DOOM 3 BFG\Fully Possessed\renderprogs\glsl-1_50\fog_skinned_vertex.uniforms
writing to: C:\Users\GuestLogIn\Saved Games\id Software\DOOM 3 BFG\Fully Possessed\renderprogs\hlsl\fog_skinned_fragment.hlsl
writing to: C:\Users\GuestLogIn\Saved Games\id Software\DOOM 3 BFG\Fully Possessed\renderprogs\glsl-1_50\fog_skinned_fragment.glsl
writing to: C:\Users\GuestLogIn\Saved Games\id Software\DOOM 3 BFG\Fully Possessed\renderprogs\glsl-1_50\fog_skinned_fragment.uniforms
writing to: C:\Users\GuestLogIn\Saved Games\id Software\DOOM 3 BFG\Fully Possessed\renderprogs\hlsl\skybox_vertex.hlsl
writing to: C:\Users\GuestLogIn\Saved Games\id Software\DOOM 3 BFG\Fully Possessed\renderprogs\glsl-1_50\skybox_vertex.glsl
writing to: C:\Users\GuestLogIn\Saved Games\id Software\DOOM 3 BFG\Fully Possessed\renderprogs\glsl-1_50\skybox_vertex.uniforms
writing to: C:\Users\GuestLogIn\Saved Games\id Software\DOOM 3 BFG\Fully Possessed\renderprogs\hlsl\skybox_fragment.hlsl
writing to: C:\Users\GuestLogIn\Saved Games\id Software\DOOM 3 BFG\Fully Possessed\renderprogs\glsl-1_50\skybox_fragment.glsl
writing to: C:\Users\GuestLogIn\Saved Games\id Software\DOOM 3 BFG\Fully Possessed\renderprogs\glsl-1_50\skybox_fragment.uniforms
writing to: C:\Users\GuestLogIn\Saved Games\id Software\DOOM 3 BFG\Fully Possessed\renderprogs\hlsl\wobblesky_vertex.hlsl
writing to: C:\Users\GuestLogIn\Saved Games\id Software\DOOM 3 BFG\Fully Possessed\renderprogs\glsl-1_50\wobblesky_vertex.glsl
writing to: C:\Users\GuestLogIn\Saved Games\id Software\DOOM 3 BFG\Fully Possessed\renderprogs\glsl-1_50\wobblesky_vertex.uniforms
writing to: C:\Users\GuestLogIn\Saved Games\id Software\DOOM 3 BFG\Fully Possessed\renderprogs\hlsl\wobblesky_fragment.hlsl
writing to: C:\Users\GuestLogIn\Saved Games\id Software\DOOM 3 BFG\Fully Possessed\renderprogs\glsl-1_50\wobblesky_fragment.glsl
writing to: C:\Users\GuestLogIn\Saved Games\id Software\DOOM 3 BFG\Fully Possessed\renderprogs\glsl-1_50\wobblesky_fragment.uniforms
writing to: C:\Users\GuestLogIn\Saved Games\id Software\DOOM 3 BFG\Fully Possessed\renderprogs\hlsl\postprocess_vertex.hlsl
writing to: C:\Users\GuestLogIn\Saved Games\id Software\DOOM 3 BFG\Fully Possessed\renderprogs\glsl-1_50\postprocess_vertex.glsl
writing to: C:\Users\GuestLogIn\Saved Games\id Software\DOOM 3 BFG\Fully Possessed\renderprogs\glsl-1_50\postprocess_vertex.uniforms
writing to: C:\Users\GuestLogIn\Saved Games\id Software\DOOM 3 BFG\Fully Possessed\renderprogs\hlsl\postprocess_fragment.hlsl
writing to: C:\Users\GuestLogIn\Saved Games\id Software\DOOM 3 BFG\Fully Possessed\renderprogs\glsl-1_50\postprocess_fragment.glsl
writing to: C:\Users\GuestLogIn\Saved Games\id Software\DOOM 3 BFG\Fully Possessed\renderprogs\glsl-1_50\postprocess_fragment.uniforms
writing to: C:\Users\GuestLogIn\Saved Games\id Software\DOOM 3 BFG\Fully Possessed\renderprogs\hlsl\stereoDeGhost_vertex.hlsl
writing to: C:\Users\GuestLogIn\Saved Games\id Software\DOOM 3 BFG\Fully Possessed\renderprogs\glsl-1_50\stereoDeGhost_vertex.glsl
writing to: C:\Users\GuestLogIn\Saved Games\id Software\DOOM 3 BFG\Fully Possessed\renderprogs\glsl-1_50\stereoDeGhost_vertex.uniforms
writing to: C:\Users\GuestLogIn\Saved Games\id Software\DOOM 3 BFG\Fully Possessed\renderprogs\hlsl\stereoDeGhost_fragment.hlsl
writing to: C:\Users\GuestLogIn\Saved Games\id Software\DOOM 3 BFG\Fully Possessed\renderprogs\glsl-1_50\stereoDeGhost_fragment.glsl
writing to: C:\Users\GuestLogIn\Saved Games\id Software\DOOM 3 BFG\Fully Possessed\renderprogs\glsl-1_50\stereoDeGhost_fragment.uniforms
writing to: C:\Users\GuestLogIn\Saved Games\id Software\DOOM 3 BFG\Fully Possessed\renderprogs\hlsl\stereoWarp_vertex.hlsl
writing to: C:\Users\GuestLogIn\Saved Games\id Software\DOOM 3 BFG\Fully Possessed\renderprogs\glsl-1_50\stereoWarp_vertex.glsl
writing to: C:\Users\GuestLogIn\Saved Games\id Software\DOOM 3 BFG\Fully Possessed\renderprogs\glsl-1_50\stereoWarp_vertex.uniforms
writing to: C:\Users\GuestLogIn\Saved Games\id Software\DOOM 3 BFG\Fully Possessed\renderprogs\hlsl\stereoWarp_fragment.hlsl
writing to: C:\Users\GuestLogIn\Saved Games\id Software\DOOM 3 BFG\Fully Possessed\renderprogs\glsl-1_50\stereoWarp_fragment.glsl
writing to: C:\Users\GuestLogIn\Saved Games\id Software\DOOM 3 BFG\Fully Possessed\renderprogs\glsl-1_50\stereoWarp_fragment.uniforms
writing to: C:\Users\GuestLogIn\Saved Games\id Software\DOOM 3 BFG\Fully Possessed\renderprogs\hlsl\bink_vertex.hlsl
writing to: C:\Users\GuestLogIn\Saved Games\id Software\DOOM 3 BFG\Fully Possessed\renderprogs\glsl-1_50\bink_vertex.glsl
writing to: C:\Users\GuestLogIn\Saved Games\id Software\DOOM 3 BFG\Fully Possessed\renderprogs\glsl-1_50\bink_vertex.uniforms
writing to: C:\Users\GuestLogIn\Saved Games\id Software\DOOM 3 BFG\Fully Possessed\renderprogs\hlsl\bink_fragment.hlsl
writing to: C:\Users\GuestLogIn\Saved Games\id Software\DOOM 3 BFG\Fully Possessed\renderprogs\glsl-1_50\bink_fragment.glsl
writing to: C:\Users\GuestLogIn\Saved Games\id Software\DOOM 3 BFG\Fully Possessed\renderprogs\glsl-1_50\bink_fragment.uniforms
writing to: C:\Users\GuestLogIn\Saved Games\id Software\DOOM 3 BFG\Fully Possessed\renderprogs\hlsl\bink_gui_vertex.hlsl
writing to: C:\Users\GuestLogIn\Saved Games\id Software\DOOM 3 BFG\Fully Possessed\renderprogs\glsl-1_50\bink_gui_vertex.glsl
writing to: C:\Users\GuestLogIn\Saved Games\id Software\DOOM 3 BFG\Fully Possessed\renderprogs\glsl-1_50\bink_gui_vertex.uniforms
writing to: C:\Users\GuestLogIn\Saved Games\id Software\DOOM 3 BFG\Fully Possessed\renderprogs\hlsl\bink_gui_fragment.hlsl
writing to: C:\Users\GuestLogIn\Saved Games\id Software\DOOM 3 BFG\Fully Possessed\renderprogs\glsl-1_50\bink_gui_fragment.glsl
writing to: C:\Users\GuestLogIn\Saved Games\id Software\DOOM 3 BFG\Fully Possessed\renderprogs\glsl-1_50\bink_gui_fragment.uniforms
writing to: C:\Users\GuestLogIn\Saved Games\id Software\DOOM 3 BFG\Fully Possessed\renderprogs\hlsl\stereoInterlace_vertex.hlsl
writing to: C:\Users\GuestLogIn\Saved Games\id Software\DOOM 3 BFG\Fully Possessed\renderprogs\glsl-1_50\stereoInterlace_vertex.glsl
writing to: C:\Users\GuestLogIn\Saved Games\id Software\DOOM 3 BFG\Fully Possessed\renderprogs\glsl-1_50\stereoInterlace_vertex.uniforms
writing to: C:\Users\GuestLogIn\Saved Games\id Software\DOOM 3 BFG\Fully Possessed\renderprogs\hlsl\stereoInterlace_fragment.hlsl
writing to: C:\Users\GuestLogIn\Saved Games\id Software\DOOM 3 BFG\Fully Possessed\renderprogs\glsl-1_50\stereoInterlace_fragment.glsl
writing to: C:\Users\GuestLogIn\Saved Games\id Software\DOOM 3 BFG\Fully Possessed\renderprogs\glsl-1_50\stereoInterlace_fragment.uniforms
writing to: C:\Users\GuestLogIn\Saved Games\id Software\DOOM 3 BFG\Fully Possessed\renderprogs\hlsl\motionBlur_vertex.hlsl
writing to: C:\Users\GuestLogIn\Saved Games\id Software\DOOM 3 BFG\Fully Possessed\renderprogs\glsl-1_50\motionBlur_vertex.glsl
writing to: C:\Users\GuestLogIn\Saved Games\id Software\DOOM 3 BFG\Fully Possessed\renderprogs\glsl-1_50\motionBlur_vertex.uniforms
writing to: C:\Users\GuestLogIn\Saved Games\id Software\DOOM 3 BFG\Fully Possessed\renderprogs\hlsl\motionBlur_fragment.hlsl
writing to: C:\Users\GuestLogIn\Saved Games\id Software\DOOM 3 BFG\Fully Possessed\renderprogs\glsl-1_50\motionBlur_fragment.glsl
writing to: C:\Users\GuestLogIn\Saved Games\id Software\DOOM 3 BFG\Fully Possessed\renderprogs\glsl-1_50\motionBlur_fragment.uniforms
writing to: C:\Users\GuestLogIn\Saved Games\id Software\DOOM 3 BFG\Fully Possessed\renderprogs\hlsl\debug_shadowmap_vertex.hlsl
writing to: C:\Users\GuestLogIn\Saved Games\id Software\DOOM 3 BFG\Fully Possessed\renderprogs\glsl-1_50\debug_shadowmap_vertex.glsl
writing to: C:\Users\GuestLogIn\Saved Games\id Software\DOOM 3 BFG\Fully Possessed\renderprogs\glsl-1_50\debug_shadowmap_vertex.uniforms
writing to: C:\Users\GuestLogIn\Saved Games\id Software\DOOM 3 BFG\Fully Possessed\renderprogs\hlsl\debug_shadowmap_fragment.hlsl
writing to: C:\Users\GuestLogIn\Saved Games\id Software\DOOM 3 BFG\Fully Possessed\renderprogs\glsl-1_50\debug_shadowmap_fragment.glsl
writing to: C:\Users\GuestLogIn\Saved Games\id Software\DOOM 3 BFG\Fully Possessed\renderprogs\glsl-1_50\debug_shadowmap_fragment.uniforms
----- Initializing Sound System ------
Setup OpenAL device and context...
 Searching for Rift Audio.
Getting openAL devices via ALC_ALL_DEVICES_SPECIFIER
Found:    OpenAL Soft on H243H-8 (NVIDIA High Definition Audio)
Found:    OpenAL Soft on HTC-VIVE-C (NVIDIA High Definition Audio)
Rift audio not found or failed to open. Attempting to initialize default openAL audio device. 
Done.
OpenAL vendor: OpenAL Community
OpenAL renderer: OpenAL Soft
OpenAL version: 1.1 ALSOFT 1.17.2
OpenAL extensions: AL_EXT_ALAW AL_EXT_BFORMAT AL_EXT_DOUBLE AL_EXT_EXPONENT_DISTANCE AL_EXT_FLOAT32 AL_EXT_IMA4 AL_EXT_LINEAR_DISTANCE AL_EXT_MCFORMATS AL_EXT_MULAW AL_EXT_MULAW_BFORMAT AL_EXT_MULAW_MCFORMATS AL_EXT_OFFSET AL_EXT_source_distance_model AL_LOKI_quadriphonic AL_SOFT_block_alignment AL_SOFT_buffer_samples AL_SOFT_buffer_sub_data AL_SOFT_deferred_updates AL_SOFT_direct_channels AL_SOFT_loop_points AL_SOFT_MSADPCM AL_SOFT_source_latency AL_SOFT_source_length
sound system initialized.
--------------------------------------
------- Initializing renderSystem --------
pdaImage size 756 840
Hudimage size 756 840
WARNING: Couldn't load image: textures/loadingicon2 : textures/loadingicon2#__0200
WARNING: Couldn't load image: textures/loadingicon3 : textures/loadingicon3#__0200
_default material not found
Shutting down OpenGL subsystem
...wglMakeCurrent( NULL, NULL ): success
...deleting GL context: success
...releasing DC: success
...destroying window
...restoring hardware gamma: success

-------------------------------------------------------------------------------------------------------------------

Not entirely sure what to do at this point.

**Comment by CarlKenner** [comment]
Try running the regular Doom 3 BFG Edition (either from Steam or the Doom3BFG.exe) first.

**Comment by KozGit** [comment]
The errors indicate the game couldn't find some of the default materials, which would appear to indicate some form of install issue ( corrupt d3bfg install/corrupt mod install )

Haven't had a response in almost a week on this issue and it hasn't replicated, so closing issue. If it persists, please reopen.

**Comment by deneuxj** [comment]
I was having the same problem. I have my steam games on two different hard drives, and when installing the VR mod, I picked the wrong installation directory. Uninstalling and reinstalling the mod at the correct location fixed it for me.
