### ISSUE TITLE
HMD Position reset button

### ISSUE THREAD

**Issue by Vaellian1020** [KozGit/DOOM-3-BFG-VR#126]
I started The game with my headset on the floor, i picked it up and now im floating really high in the air. i understand i could restart the game with the HMD on my head, but i was reading around and apparently there's a button that resets the position. i can't find anything on the topic, i found one that said it was the grip buttons, but that makes me crouch or reload

**Comment by Vaellian1020** [comment]
Also realized i should mention i'm on the vive

**Comment by KozGit** [comment]
You may want to give the readme a look - there's a lot of good information in there, including the default controller bindings for each hmd and how to change them.   You can bind the Reset HMD orientation command to any key or button you like in  settings->controls->key bindings.  You can also use the Recenter View voice command.

From the readme:

Recenter view:
	
	    This resets the view height to your current view position,
	    and makes the player and the view face your current view direction.
	    Useful for switching between sitting and standing mode of if the 
	    player body becomes disoriented.
	    
	  Say:
	      Reset View
	      Recenter View
	      Reset HMD Orientation
	      Reset HMD View

Hope this helps.
