### ISSUE TITLE
Left Handed aiming + Right touchpad teleportation

### ISSUE THREAD

**Issue by borisv13** [KozGit/DOOM-3-BFG-VR#128]
It appears the following set-up is not possible (if it is, please instruct me and close the issue):
Left hand Weapon + Right touchpad teleportation

The result is: I'm a lefty, I need to aim with my left hand. The game then forces me to use left touchpad for teleportation. This is uncomfortable. Also, every time I touch the left touchpad to go to teleport, the character first moves (due to touchpad movement).

**Comment by KozGit** [comment]
If you are using the weapon slots to change weapon hands, by default the controls dont change, as a lot of people are used to using the left hand for movement.

To change this behavior, from the console ( press ~ to open console ) type vr_handSwapsAnalogs 1 < enter >.  This will cause the analog controls to swap when swapping hands using the slots.

If you didn't swap hands using the weapon slots, you just changed the weapon hand in the menu, you can just re-bind the controls however you like.  Go to settings->controls->keybindings.  Select the action you want to change, click or press enter, then press the button or touchpad direction you want to map to that action.  

There is a good amount of info in the readme on rebinding controls - you should be able to define a control scheme you like.

**Comment by borisv13** [comment]
How do I reset EVERYTHING?

**Comment by KozGit** [comment]
If you delete the .cfg file from your savegame directory and start the game, it will reload the defaults that shipped with the mod.

**Comment by CarlKenner** [comment]
> If you didn't swap hands using the weapon slots, you just changed the weapon hand in the menu

The menu now has the same behaviour as the weapon slots. It will swap the controls according to vr_handSwapsAnalogs.

**Comment by borisv13** [comment]
I'm trying very hard to make sure I'm not being dumb.
Where is the save game directory?
I read looked in the Readme and docs - did not find information.
Google did not help either.

**Comment by CarlKenner** [comment]
No, you're not being dumb. It's:

`%UserProfile%\Saved Games\id Software\DOOM 3 BFG\Fully Possessed`

**Comment by borisv13** [comment]
I got the touchpad and movement figured out!
New question:
Why does my gun get replaced with my fist (and vice versa) every couple seconds?
It's been happening since I picked up the gun in the very beginning. 
I'm now at the part where enemies first appear. It still happens. I'll be trying to shoot, and the gun gets replaced by my fist, and then my fist will again be replaced by my gun, roughly 10 per minute.
Makes the game unplayable, obviously.
Thank you.

**Comment by KozGit** [comment]
Your microphone is picking up up something that windows speech recognition is interpreting as  'fists' - could be sound from your speaker/headphones or even your breath.  You can try turning down the sensitivity of your mic, disabling voice commands, or editing the 'fully possessed/dict/voice.dict' file  and either remove 'fist' and 'fists' or change them to something like 'weapon fists'.

Glad you got the controls figured out.  Again, don't forget the readme file - there's lots of good info in it.

I'm going to close this issue as the movement mapping seems to be resolved for you.

**Comment by CarlKenner** [comment]
Could people please post new questions in new issues!
It makes the issue tracker impossible to use if people post different issues on issues that have already been fixed.

There are three possible reasons your gun is getting replaced with your fist and vice versa.

If you're reloading your gun with your hand near your hip, you'll get that effect due to holster slots.

If you're comfort mode turning a lot with the right analog stick/pad, you'll sometimes bump up or down which triggers Next Weapon or Previous Weapon.

The voice recognition sometimes hears "fist", "fists", "pistol", or even "the artifact" when you don't say them, and changes weapons. This happens more if the microphone is picking up sound from your speakers.

**Comment by borisv13** [comment]
Turns out it was relevant to this issue - in case anyone else is trying for the same config as me.
Since I mapped R touchpad to Teleport, I had to unmap "previous weapon" and "next weapon" from the Right Touchpad Down and Right Touchpad Down mappings.
Thanks for the help! I didn't expect so much to be configurable - turns out it was all there I just didn't look hard enough.
