### ISSUE TITLE
Hands don't line up with actual hands on Vive

### ISSUE THREAD

**Issue by CarlKenner** [KozGit/DOOM-3-BFG-VR#14]
On the HTC Vive in Steam VR, the virtual hands are too far forward. The tracking point on the Vive controller is near the touchpad, but the centre of your real hands will be further back on the controller.

Also the angle is slightly wrong. I think the Vive considers no rotation to be with the handle horizontal, while the Touch in the Oculus SDK considers no rotation to be the top horizontal while the handle is at an angle. Which means it's off by about 37 degrees.

I don't know if you have HTC Vive or not to test.

I don't know whether the assets in your downloads are different for the HTC Vive and the Rift.

**Comment by KozGit** [comment]
For the weapons, these can be adjusted.  vr_motionWeaponPitchAdj changes the pitch of the weapon, and vr_motionFlashPitchAdj changes the pitch of the flashlight.   This pitch varies between touch and vive, which is one of the reasons I just switched to having unique config files for each API.

cvars vr_vcx, vr_vcy, and vr_vcz let you correct for the difference it the tracking point on the controller vs where your hand actually is.

I do want to add corrections to the 'pointy finger' used when touching guis so the finger tip can line up better with real life.

**Comment by CarlKenner** [comment]
I'm glad that feature is already present. I didn't realise the default config was different. I've been testing both versions with the same files.

It's not just about the API though. We used to be able to use Oculus Touch through Steam VR, and I plan to add an option to support that again. In Dolphin VR, I check m_strDriver, which will be "oculus" for the Rift and Touch, "lighthouse" for the Vive, and probably something else for other controllers.

**Comment by CarlKenner** [comment]
I assume this has been fixed now.
