### ISSUE TITLE
Player head on backwards after loading from RBDoom / Leyland

### ISSUE THREAD

**Issue by CarlKenner** [KozGit/DOOM-3-BFG-VR#143]
I've been struggling with this issue, and I'm hoping @KozGit can help. After loading a saved game from Leyland's mod, the player's head is on backwards and at a weird angle, and doesn't respond to head tracking.

Note that the head is a separate entity, which is created before the idPlayer::Restore function is called, but is not filled with any data until it's own AFAttachment::Restore function is called later as it goes through the list of entities.

I tried some things to fix it, but I only managed to make the head disappear completely.

**Comment by KozGit** [comment]
Can you attach the save game you are having issues with and I'll test?

**Comment by KozGit** [comment]
Without looking at this yet, I'm guessing player.neckJoint is not being properly initialized with a valid joint handle after loading.

The normal init for the player looks in the player.def for the val associated with key "bone_neck".  ( this should really always return 'neckcontrol'.  Note that bone_neck is not defined is the base doom player.def, it was added with this mod) and queries the animator for the jointhandle associated with this value.

 You should be able to query the animator for the jointhandle for the value "neckcontrol" and assign the jointhandle to neckJoint.   Also note that the neckJoint is part of the player entity, not the head entity.

**Comment by KozGit** [comment]
I installed rbdoom and saved a game - see the issue, will look at this now.

**Comment by KozGit** [comment]
This is a little strange.  It's behaving as if the player anims are using a joint list from vanilla doom. ( The player model has a bunch of new joints for all the fingers in this mod).

Pulling a joint list from the player model shows all the joints.  If I re-bind the head entity to the neck joint, i can control it again, but the orientation is wrong, at the head moves when the right index finger anim plays ( shoot the gun or pose is changed).  Trying to figure out how to look at the joint hierarchy for a specific animation in memory.

**Comment by CarlKenner** [comment]
Does the right index finger move when the right index finger anim plays?
Maybe this is just a problem with the head object's own animation and joint list? I don't really know how animations work.

**Comment by KozGit** [comment]
Alright, I put in a workaround for this. 

It was the copyJoints.  Looks like you started to implement code to recreate them during restore, but it wouldn't work because the anims/joints for the head entity hadn't been loaded from the save game yet.

I added idPlayer::RecreateCopyJoints that rebuilds a valid copy joint list.  I currently have it being called from idPlayer::UpdateNeckPose the first time UpdateNeckPose() is called, but maybe this would be better if moved to the end of the save game restore?

**Comment by CarlKenner** [comment]
Excellent!
I just added a warning message with restart or continue options when loading a saved game from another mod to avoid the other glitches.

**Comment by CarlKenner** [comment]
This is fixed for the base game, but not for the Resurrection of Evil expansion.

**Comment by KozGit** [comment]
I fixed this, the moved the call to recreatecopyjoints to the end of execute map change.  (It actually worked with roe before, but it only recreated the joints the first time you loaded a save game, now it does it every time. Will push shortly.

**Comment by KozGit** [comment]
This should be resolved. Moved the call to rebuild the copyjoints to execute every time a level is loaded, to ensure list is always valid.
 
Closing issue.
