### ISSUE TITLE
Game crashes at conclusion of Alpha Labs Administration

### ISSUE THREAD

**Issue by AchillesOne** [KozGit/DOOM-3-BFG-VR#150]
Game consistently crashes to desktop at the conclusion of Alpha Labs Administration.  Unable to progress to next level.

**Comment by KozGit** [comment]
You probably have the all in one texture pack installed.  This is a known issue with that pack.

Just delete the 'generated' folder in the 'base' directory of your doom 3 installation and you should be good to go.

**Comment by KozGit** [comment]
Let me know if you are still having this issue - closing for now - haven't had a response in a while.
Thx.
