### ISSUE TITLE
OpenGL keeps causing my game to crash on start up.

### ISSUE THREAD

**Issue by Deathtone2** [KozGit/DOOM-3-BFG-VR#152]
So I install the VR mod with a Texture pack and no matter what I try the game keeps causing this OpenGL error.  
I have spent and pretty good amount of time trying everything I can find on google to try and fix it but I can't.

If I run the normal game it works but if I try to play the VR version of the game the error comes up.

I have SLI GTX 960 x2 
Intel i7 quad core 4790 processor 4.00 ghz.

Please i Have reinstalled the game reloaded my graphics drivers and everything and still the same result.  Please help.

**Comment by KozGit** [comment]
Can you post the error please, or a screenshot of the crash dump?

**Comment by KozGit** [comment]
I haven't seen a response to this, so I'm going to close this issue for now.

Here's how to log the game startup:

Create a shortcut to Doom3BFGVR.exe
Right click on the shortcut, go to properties.
In the target field, add +set logFile 2 to the end - be sure to leave a space after .exe and before +set
Click apply, then ok.
Double click shortcut to launch the game.

The log file will be stored in c:\users(your user name)\saved games\id software\doom 3 bfg\base\qconsole.log

If you can post a copy of the startup log, feel free to open a new issue, thx!
