### ISSUE TITLE
Frustrated with installation.

### ISSUE THREAD

**Issue by TheSelectedLamb** [KozGit/DOOM-3-BFG-VR#154]
these installation guides are incomplete. I have doombfg installed through Steam. I have DOOM-3-BFG-VR-master.zip unzipped in the main directory, and still i have no .EXE file to be found anywhere. 
Please pet me and tell me everything will be okay.

**Comment by KozGit** [comment]
The installer is available on the releases page. 

 https://github.com/KozGit/DOOM-3-BFG-VR/releases

Download and run https://github.com/KozGit/DOOM-3-BFG-VR/releases/download/V0.021-Alpha/Doom3BFGVR_Fully_Possessed_Alpha021.exe

**Comment by TheSelectedLamb** [comment]
Thank you so much! this will jettison me through that part of the installation... now to get it to work!
