### ISSUE TITLE
Loss of sound after windows 10 update

### ISSUE THREAD

**Issue by paturiku** [KozGit/DOOM-3-BFG-VR#159]
Whether through headphones or speakers I get no sound in the mod but I get sound in oculus home or outside of vr. Also get sound when playing unmodded doom 3 bfg edition. Tried uninstalling and reinstalling the mod. All started the day after a big windows 10 update but I'm not computer savvy enough to do more than guess.

**Comment by petes117** [comment]
Check the SteamVR audio settings are set to the correct playback device, it likely got reset by that windows update

**Comment by KozGit** [comment]
I'm assuming you're using a rift.

1st thing, from console in the game ( press ~ to open console ) 
type vr_forceOculusAudio 1 and press enter.  Then exit the game and restart to see if it helps.

If that doesn't work, try going into oculus home ( on your desktop ) Click the gear icon, go to settings, devices,rift.  Go to audio output in VR, and set it to Rift Headphones ( not Both audio mirroring ) 

Let me know if any of that helps.  Also, go to control panel->sound and let me know what the default audio device is.

**Comment by paturiku** [comment]
Based on the advice of a commenter on youtube I activated the mirroring sound option. I had my doubts it would do anything because I use third party headphones (turtle beach) not the ones that come packed with the rift. On the very next boot up the sound was working. HOWEVER I can't be completely sure this was the result of activating mirroring. Windows 10 sent out a small update the day or two after the big one that might have something to do with it. Either way would just be a guess. I could switch off mirroring to see what happens but I prefer not to experiment after things seem to be working.

**Comment by KozGit** [comment]
Glad you got it sorted out!  I'm going to go ahead and close this issue.
