### ISSUE TITLE
Screen ist tilting when turning Head

### ISSUE THREAD

**Issue by neitey** [KozGit/DOOM-3-BFG-VR#161]
##After been hit by an enemy, the screen acts weird. When I turn my head left or right the world seems to tilt to the side. only occurs after been hit the first time. Version  0.21 running latest update of SteamVR. 

Edit: Seems to get worse after been hit more often. Problem vanishes after restarting level. Did a clean reinstall of Doom and Mod - no change.

EDIT SOLVED: I deleted all files in /user/"username"/savegames/fullypossessed - now works perfekt! thx for the great VR mod

**Comment by KozGit** [comment]
I'm going to close the issue, as you seem to have resolved it, but I admit to being curious as to what could have caused this.  If it happens again, if you think about it, save a copy of the .cfg files in the fully possessed save game directory so I can take a look at them. Thx! ( Glad you like the mod :) )

**Comment by neitey** [comment]
Thx for your reply. First of all I really like what you did with this mod
is Doom. Doom works so well in VR - thanks to your work. I doesn't even
look like a mod. the venues, options for customization,in-game VR
menus/Pda, weapon holstering, graphics options, locomotion, speech
recognition, character options ... the list goes on.

this is amazing, you thought of everything. No other Game made for VR has
this many useful options.

ok enough of that.

If it happens again. I will send my config. played 4 hours in the last days
and no more issues.

Only ROE isn't loading beyond level 1. maybe something to do with the
Hi-Def HD pack?

cheers
from Bavaria

Am 26.05.2017 5:45 nachm. schrieb "KozGit" <notifications@github.com>:

**Comment by KozGit** [comment]
Could be the hi-def pack - If you haven't already, try deleting the 'generated' folders in both the 'fully possesses' directory and in 'base'  - the game will re-create them the next time it's run. ( It may take a little longer than usual to start a level the first time though).  

If it is crashing to the menu screen with the blue text, scroll up through the text to see if you can find the error.
