### ISSUE TITLE
PDA/Menu not displaying correctly

### ISSUE THREAD

**Issue by chuckus69** [KozGit/DOOM-3-BFG-VR#166]
I just installed the latest version on a clean install of DOOM 3 BFG. It's my first install ever. When I activate the PDA or attempt to use the in-game menu, the blue background texture with "UAC-PDA" is displayed backwards with no other menu elements visible. The menus and PDA technically work but I can't actually see what I'm clicking. 

I tried searching for people with similar issues but haven't found any. Has this ever popped up before?

**Comment by KozGit** [comment]
It seems like the updated models may not have been installed - how did you install the mod?

**Comment by chuckus69** [comment]
I downloaded the latest exe installer from GitHub. It seems I may need to try to redownload the mod and reinstall. I'll post the results once I've had a chance to try that.

**Comment by chuckus69** [comment]
I tried installing over the existing install after downloading the 021 exe again. That didn't work.

So I downloaded the 020 installer and installed that over the existing install. That didn't work.

I uninstalled Doom 3 VR Fully Possessed and reinstalled with 020 installer. Now the PDA works. 

I installed 021 over 020 and it still works although I'm not sure if I'm running the latest version now. 

I am afraid to uninstall everything and try the 021 installer again but I can if you would like me to test it for you.

**Comment by KozGit** [comment]
For now, I would leave it if its working.  When 022 is released, we can test it then.  This is a curious issue, haven't seen it reported before. Thanks for the offer to help!

**Comment by KozGit** [comment]
Closing issue as it appears to be working, and have not seen a duplicate issue. Will re check when 022 is released.  If anyone else experiences this please re-open issue.

**Comment by glaucobacchi** [comment]
I am experiencing exactly the same issue. I too used a fresh install of
Doom3BFGVR_Fully_Possessed_Alpha021
over a fresh install of Doom3BFG.



I do not have rights to re-open this issue. I will wait and try 22 before trying older versions.
