### ISSUE TITLE
Tracking doubled when 45 FPS, so world isn't locked to chaperone when I move my head

### ISSUE THREAD

**Issue by CarlKenner** [KozGit/DOOM-3-BFG-VR#17]
When I move my head, the virtual world should stay locked to the real world (as evidenced by the chaperone/guardian grid)... but it doesn't. It feels weird and could cause motion sickness.

**Comment by KozGit** [comment]
Which hmd/API
Thought I had addressed this, and don't experience this on my two dev machines on either API)
Do you experience this constantly or is it intermittent?

**Comment by CarlKenner** [comment]
I noticed it on the Oculus Rift in native mode. I don't know if it's constant or not, I haven't tested room scale much.

**Comment by KozGit** [comment]
When you get a chance, try setting com_smp to 1 and let me know if the issue clears when running single threaded. ( You notice this primarily on rotation?)

**Comment by CarlKenner** [comment]
Oculus Rift / Oculus SDK
intermittent (but very common)

It's NEVER on rotation, only on position. And it's not the issue you're thinking of with lag (I used to have that issue in Dolphin VR). It's not lagging, it's just moving the view too far for every head movement.

Sometimes it gets into the mode where the virtual world moves too far for any physical movement (about twice as far). So I step 30cm to the right in the real world, move 30cm relative to the Chaperone, but 60cm relative to the virtual Doom world. I can't work out what causes it. BUT I can usually fix it by using the joystick to move virtually. After that it goes back to 1-to-1 tracking for a while.

I'm encountering this in Mars Underground.

**Comment by KozGit** [comment]
Ahhh!! Think I know what this is - check if ASW has kicked in when this is happening.

**Comment by CarlKenner** [comment]
I can't tell if ASW has kicked in. The ASW shortcut keys aren't working for me.

Oh, and com_smp doesn't seem to make a difference.

Anyway, what I guess is happening is it is reading the position tracking difference once per frame, and adding that difference to your position 90 times per second.

**Comment by CarlKenner** [comment]
This code in Player.cpp assumes it always gets called at 90 FPS:
```
				newBodyOrigin = bodyOrigin + bodyAx[0] * commonVr->poseHmdBodyPositionDelta.x + bodyAx[1] * commonVr->poseHmdBodyPositionDelta.y;
				//newBodyOrigin.z = 0.0f;
			
				commonVr->motionMoveDelta = newBodyOrigin - bodyOrigin;
				commonVr->motionMoveVelocity = commonVr->motionMoveDelta / ( ( 1000 / commonVr->hmdHz ) * 0.001f);
```Even if that assumption is correct, poseHmdBodyPositionDelta is often only reset at 45 FPS by FrameStart.

Anyway, I just fixed the bug by resetting the remaining movement to 0 after I consume it. Now it works at any framerate.
