### ISSUE TITLE
Is vr_openvr.cfg the file I would need to copy, to copy my settings to another computer?

### ISSUE THREAD

**Issue by tsr22** [KozGit/DOOM-3-BFG-VR#170]
If I were going to give a friend my vr cfg, is it the one located at:

`Saved Games\id Software\DOOM 3 BFG\Fully Possessed\vr_openvr.cfg`

?

**Comment by KozGit** [comment]
If you are using a vive, then yes, that is your config file.  You will need to copy it to the save game directory on the new machine.

**Comment by tsr22** [comment]
Thanks Koz! Anywhere to donate to you guys for your hard work?

**Comment by KozGit** [comment]
Not accepting donations for this, thanks for the offer tho.  Glad you're enjoying it!

( Closing issue )
