### ISSUE TITLE
Is it possible to make content mods for this fork ?

### ISSUE THREAD

**Issue by motorsep** [KozGit/DOOM-3-BFG-VR#178]
Is it possible to make content mods for this Doom 3 BFG fork? (stuff like new maps with new textures; new models; update AI scripts; etc.)

**Comment by KozGit** [comment]
Just to make sure I understand the question, are you asking if it's ok to make content mods, or are you asking if its technically possible?  ( The answer to both questions is yes, but I'd like to answer more fully if you can tell me what you're trying to do. ) 

Thx!

**Comment by motorsep** [comment]
@KozGit It's the latter. I've worked with Doom 3 BFG engine for a long while and I know that out of the box it doesn't work with mods (content mods, since the architecture is different from old Doom 3 and DLL mods aren't compatible with new engine). RBDoom 3 BFG doesn't quite work with mods either, despite its authors claims (I couldn't really get it to load any content mods, even basic ones).

Btw, our Doom 3 BFG fork has some goodies, in case you want to port them over into your VR branch :)

https://github.com/motorsep/StormEngine2

**Comment by KozGit** [comment]
This mod is built off of an older version of RBDoom3.  Nothing was changed  to allow additional modding.  You can add new textures and models ( I had to change some for this mod ).  Also, some of the hi-def texture packs work ( with some bugs ) with this and RBDoom.    Obviously, original doom 3 mods that included a modded .dll wont work with with BFG as you mentioned.

I haven't tested using new maps with BFG yet.  It's something I want to look at, but I'm still trying to implement all the VR specific features so I haven't really had much time to look at it.

Gloss map support huh? Sweet!  I didn't have time to go thru the code, how did you wind up implementing them?

**Comment by motorsep** [comment]
@KozGit I didn't - I had 2 ex-ID guys contracted to implement vast amount of new features and bug fixes. Eventually ran out of money and they ran out of enthusiasm, and the project died.

**Comment by KozGit** [comment]
Closing issue as question was addressed.
