### ISSUE TITLE
[FEEDBACK] Chaperone/guardian bounds appear black - very hard to see in-game

### ISSUE THREAD

**Issue by motorsep** [KozGit/DOOM-3-BFG-VR#183]
Chaperone/guardian bounds appear black in-game. Very hard to see :(

Oculus has bound grid colored in glowing teal color in Oculus Home and in any other game/app I tried. Is it possible to do the same for this game ?

**Comment by KozGit** [comment]
This chaperone color is adjustable go the in game menus.  Black chaperone is part of a comfort and, you can have it on all the time to give a fixed frame of reference.  The readme file has good Info about all the config options. Closing issue as is config related, feel free to reopen if the issue can't be addressed via the menus
