### ISSUE TITLE
Doom BFG not launching - default material not found

### ISSUE THREAD

**Issue by KinkyJalepeno** [KozGit/DOOM-3-BFG-VR#205]
I'm getting this error in the launch window when I launch, I carried out the install ect as per Face_Palms' vid to the letter.

I have attached the error log from the launcher and would appreciate any advice to get this working,

~Kinky
[Doom BFG log.txt](https://github.com/KozGit/DOOM-3-BFG-VR/files/1254342/Doom.BFG.log.txt)

EDIT: I'm using a Rift if it makes any difference

**Comment by KozGit** [comment]
Did by any chance you install one of the hi def texture packs?  The default material is part of the normal d3bfg install, it wasn't changed by this mod.  If all else fails, try deleting then reinstalling d3bfg in steam, then download the .zip file from the releases page and extract it into the d3bfg directory in you steam library.

**Comment by KinkyJalepeno** [comment]
Oh hold on I know what I did wrong..
I renamed my original "base" folder then dropped in the new one.

I should have dropped in the new one and let it over-write where it needed to..  DUH

**Comment by KinkyJalepeno** [comment]
Ok now the game is working which is great, only issue now is my actual hands in game are about 8ft to the right of where I actually am in the world.

Any idea's?

**Comment by KinkyJalepeno** [comment]
NVM had to turn on 3rd sensor - all good here :)

**Comment by KozGit** [comment]
Glad it's working, closing issue as seems to be resolved.
