### ISSUE TITLE
Won't launch. Error given is "Couldn't load default.cfg"

### ISSUE THREAD

**Issue by bfhouse** [KozGit/DOOM-3-BFG-VR#208]
After installing the current .exe version and attempting to launch it via the desktop shortcut(with and without steamVR launched) it will bring a blue error window with the header: Couldn't load default.cfg.
Error Dump below:

WARNING: CVar 'developer' declared multiple times with different initial value
QA Timing INIT: 000056ms
DOOM 3 BFG VR 1.0.3.1401 win-x86 Mar  9 2017 18:56:27
3696 MHz Intel CPU with MMX & SSE & SSE2 & SSE3 & HTT
Winsock Initialized
Found interface: {09013F30-2110-4CD9-9D16-8AA2EA2E3333} Realtek PCIe GBE Family Controller - 192.168.94.84/255.255.255.0
Found interface: {BE30FE9C-222D-4EBE-9734-559FED9B5763} Bluetooth Device (Personal Area Network) - 0.0.0.0 NULL netmask - skipped
Found interface: {61C0CD01-7D4F-464C-9FB2-0835860FCF47} Qualcomm Atheros AR9485 Wireless Network Adapter - 0.0.0.0 NULL netmask - skipped
Found interface: {03374261-6134-4F8E-B5B3-95F1ECF6BE85} Microsoft Wi-Fi Direct Virtual Adapter - 0.0.0.0 NULL netmask - skipped
Sys_InitNetworking: adding loopback interface
doom using MMX & SSE for SIMD processing
enabled Flush-To-Zero mode
enabled Denormals-Are-Zero mode
------ Initializing File System ------
Current search path:
C:\Users\Ben House\Saved Games\id Software\DOOM 3 BFG/Fully Possessed
c:\program files (x86)\steam\steamapps\common\DOOM 3 BFG Edition/Fully Possessed
C:\Users\Ben House\Saved Games\id Software\DOOM 3 BFG/base
c:\program files (x86)\steam\steamapps\common\DOOM 3 BFG Edition/base
file system initialized.
--------------------------------------
Unknown command 'vid_restart'
Couldn't load default.cfg
Shutting down OpenGL subsystem
...wglMakeCurrent( NULL, NULL ): failed

**Comment by KozGit** [comment]
Default.cfg is part of the normal D3BFG install, so something went wrong during the install pro ess. Try this: delete the 'fully possessed' directory from the doom 3 install directory.  In steam, verify the d3bfg game cache, then make sure vanilla D3BFG without VR works by launching through steam.  Now go to the releases page and download the .zip package of the mod.  Unzip into the doom 3 install directory, normally c:\program files (x86)\steam\steamapps\common\DOOM 3 BFG Edition

Now try launching the VR .exe

**Comment by bfhouse** [comment]
That fixed it.
