### ISSUE TITLE
Mic Commands stop working

### ISSUE THREAD

**Issue by Wolverine6913** [KozGit/DOOM-3-BFG-VR#211]
After playing the game for a few minutes, the voice commands for weapons and flashlight stop working. Can you help?

**Comment by jdawgzim** [comment]
Check out the README.txt . The voice command "Start Listening" can re-enable voice commands.

**Comment by Wolverine6913** [comment]
Thank You 

    On Tuesday, September 12, 2017 11:14 AM, jdawgzim <notifications@github.com> wrote:
 

 Check out the README.txt . The voice command "Start Listening" can re-enable voice commands.—

**Comment by KozGit** [comment]
If you have any more issues with this feel free to open a new issue, thx.
