### ISSUE TITLE
Run always on?

### ISSUE THREAD

**Issue by skipperoni** [KozGit/DOOM-3-BFG-VR#213]
I'm playing the game without the comfort options on (meaning no teleport), and my movement has been working well so far, but recently the game blacked out for a second, and when it came back it was toggled to always run. I'm using the rift controllers, so running is mapped to the left trigger, but now it's toggled on by default and I cannot figure out how to switch it back. It's too disorienting like this.

Can anyone help? Thanks!

**Comment by KozGit** [comment]
There are voice commands to toggle running/walking - you can say 'Start Walking' or 'Stop Running', for example. Let me know if this helps.

**Comment by KozGit** [comment]
If you are still having this problem, feel free to open a new issue. Closing this one as no additional updates. Thx
