### ISSUE TITLE
[Question] How to enable head-bobbing ?

### ISSUE THREAD

**Issue by neodraig** [KozGit/DOOM-3-BFG-VR#214]
As one of the lucky ones that are not sick in VR, I would really appreciate to activate the head-bobbing.
Is it possible to do that ?

Gliding over the ground kinda breaks the immersion to me, and having the head-bobbing would really improve it (in my opinion).

I know it is not advise to use head-bobbing in VR as it makes some people sick, but as a person who's not sick in VR, I would really appreciate to have it.

Thanks.

**Comment by 10101000** [comment]
Try setting the following cvars in the console or in your autoexec.cfg:
```
set pm_crouchbob 0.5
set pm_walkbob 0.3
set pm_runbob 0.4
set pm_runpitch 0.002
set pm_runroll 0.005
set pm_bobup 0.005
set pm_bobpitch 0.002
set pm_bobroll 0.002
```
For reference see: [SysCvar.cpp](https://github.com/KozGit/DOOM-3-BFG-VR/blob/master/neo/d3xp/gamesys/SysCvar.cpp)

**Comment by KozGit** [comment]
@10101000 Thanks for posting!  Going to close the issue as there hasn't been any follow up from the op.
