### ISSUE TITLE
Player View Height Resetting upon death

### ISSUE THREAD

**Issue by DefendYourBase** [KozGit/DOOM-3-BFG-VR#217]
By default the view height is 68. I have to almost always set it to 40 to have my blue grid align with the floor but every time I die, load a save, or start the game over it resets  to 68. Is it possible to at the "least" have it not reset after each death?

**Comment by 10101000** [comment]
I suspect that the master branch already has a [fix](https://github.com/KozGit/DOOM-3-BFG-VR/commit/a71061245a279fa0030301b14114f5739f42460d).

**Comment by DefendYourBase** [comment]
oh wow ok. Thanks man. I didnt see it under the commits part. I checked issues open and closed tickets and didnt see it. Otherwise i wouldnt have asked. Sounds like next update might fix it O.o Best freaking VR game experience ever.

**Comment by 10101000** [comment]
No problem, I've compiled an [unofficial V0.022-Alpha](https://github.com/10101000/DOOM-3-BFG-VR/releases/tag/V0.022-Alpha) if you'd like to test it. I agree, this mod is exceptional!

**Comment by DefendYourBase** [comment]
Excellent. Sure will. I noticed the download currently was v.021 but the readme on webpage says it has updates for v.022. Is that what is in this one (plus other stuff?)?

**Comment by 10101000** [comment]
The readme on the webpage defaults to the master branch for which v0.022 hasn't been released yet. The current download is compiled using the [V0.021-Alpha](https://github.com/KozGit/DOOM-3-BFG-VR/tree/V0.021-Alpha) tag. Notice the readme states the correct version there. The version I've compiled includes all commits up to 0.021 plus all unreleased commits made after. To see these changes you can use the GitHub [compare feature](https://github.com/KozGit/DOOM-3-BFG-VR/compare/V0.021-Alpha...master).

**Comment by DefendYourBase** [comment]
excellent. i have never used github before. never heard of it till now actually. on your v.022 should i report bugs? and where?

**Comment by 10101000** [comment]
Since my build is unofficial and 022 hasn't been released yet, I'd suggest waiting for the official release before submitting any bug reports. However before then I'll be happy to provide new builds as new commits are added.

**Comment by DefendYourBase** [comment]
Ty

**Comment by DefendYourBase** [comment]
Going to close this now.
