### ISSUE TITLE
problems with movement

### ISSUE THREAD

**Issue by Trazziz** [KozGit/DOOM-3-BFG-VR#230]
when i use the touch pad for movement, the doom guy wanders off in 3rd person until i stop then the camera snaps back on to him. have i set something up wrong?

**Comment by T0mputer** [comment]
Go to settings/VR Option/Comfort/set motion sickness aid to not 3rd person

**Comment by T0mputer** [comment]
helpfull video about options here 
https://www.youtube.com/watch?v=83kdr7D-DJ0&feature=youtu.be

**Comment by Trazziz** [comment]
perfect! thank ye kindly sir!

**Comment by KozGit** [comment]
Looks like you sorted this out, closing this issue, thanks!
