### ISSUE TITLE
"Reduce FOV" comfort option - stereo overlap issue

### ISSUE THREAD

**Issue by FolkSong** [KozGit/DOOM-3-BFG-VR#246]
When the FOV is reduced, it should only affect the peripheral vision. It currently reduces the FOV on each eye individually, include the inside edges, which leads to black lines in the middle of your vision and stereo overlap issues as your eyes and brain try to sort out what's happening. 

This could be fixed simply by not applying the reduction to the inside edges (right edge of the left eye, and left edge of the right eye).

From playing Fallout 4 VR I found that this comfort option is actually very effective for me, so it would be nice to be able to use it in other games such as Doom 3.

**Comment by KozGit** [comment]
Hey, sorry for the late reply.  This has actually been fixed in the upcoming release - as well as implementing the reduced FOV when smooth turning.  Also added the option to enable motion blur when smooth turning - some people have commented this can help as well.

**Comment by FolkSong** [comment]
That sounds great, thanks! I'll look forward to that in the next release.
