### ISSUE TITLE
Can we get a new executable?

### ISSUE THREAD

**Issue by Slinkywinky** [KozGit/DOOM-3-BFG-VR#248]
The main reason I want this is fot the ptt. Kind of tired of the voice command system wigging out on me every time someone talks to me.

**Comment by KozGit** [comment]
Working on getting the new release out, no specific ETA though.  In the interim, you could edit the voice.dict file in d3bfg->Fully Possessed->dict directory, and edit the phrases that are recognized to something not as easily misinterpreted ( preface each name with 'weapon' for example ) I know it's not ideal.

If you're using SteamVR, I know some people have used the push to talk feature in the 'Advanced Settings' app (  https://github.com/matzman666/OpenVR-AdvancedSettings/releases ) for this purpose.

**Comment by KozGit** [comment]
There are a few issues open regarding the next release, closing this one to avoid duplication. Thx!
