### ISSUE TITLE
Still in developement? 

### ISSUE THREAD

**Issue by Nordomus** [KozGit/DOOM-3-BFG-VR#250]
Just making sure, new version was suposed to be out around july or something, I don't even remember when exactly.

**Comment by cercata** [comment]
Yes, at least 2 months ago:

https://github.com/KozGit/DOOM-3-BFG-VR/issues/215

**Comment by KozGit** [comment]
Yep, still in development, just slow going - the holiday season left me with virtually no free time to work on this.  Now that things are returning to normal, I'm hoping to wrap some things up soon.

**Comment by jtslade77** [comment]
KozGit, we would love to chat with you for an episode in the near future about the development of Doom3BFGVR and your thoughts/experiences on porting games to VR. 
Damon W. 
Content Producer 
Everything Vive Podcast 
damon@everythingvive.com

**Comment by jdawgzim** [comment]
I'm excited to promote this mod on the next release!  You're so close to the next release right?  Do you need more beta testers?

**Comment by KozGit** [comment]
There are a few open issues about the next release, closing this one to avoid duplication. Thx!
