### ISSUE TITLE
Lag.

### ISSUE THREAD

**Issue by nitrosucc** [KozGit/DOOM-3-BFG-VR#257]
Just starting this mod and i already love it but every 1 or 2 minutes the framerates drop really bad and it shows the oculus loading icon.

Please help!

**Comment by KozGit** [comment]
What's your setup? ( HMD / cpu / gfx card )   What are you hmd supersampling settings, and what's pixel density set to in the game menus?  Have you changed any of the game settings?

**Comment by nitrosucc** [comment]
Im using a oculus ready pc asus g11cd and the graphics card is a nvidia gtx 1060 (i think) i messed with the settings a bit and i even did lower the pixel density

**Comment by nitrosucc** [comment]
Ill leave more detail once im at home

**Comment by nitrosucc** [comment]
im using oculus rift
Intel Core i5 (6th Gen) 6400 / 2.7 GHz
gtx 1060

**Comment by KozGit** [comment]
Lets start by setting the options to a safe level - in the game, go into the menu and disable MSAA, then drop the pixel density to 1.0.  Restart the game, and see if performance has improved.  

I'm surprised you're seeing the loading icon - normally if there is a frame hitch, atw/asw will take care of it and you will never even notice.   Is there any chance this is the game is autosaving?  ( This happens a few times in the beginning - right around the time you talk to sarge, and right after all hell breaks out. ) The game will pause for a sec while autosaving  during a level.

**Comment by KozGit** [comment]
No updates in a while, and no further reports of this problem, so I'm closing the issue.  Please re-open if it's still happening.
