### ISSUE TITLE
Flashlight disapeared right before Labs sector 3 loading

### ISSUE THREAD

**Issue by skully213** [KozGit/DOOM-3-BFG-VR#261]
Hello, the flashlight just disapeared suddenly right before Labos sector 3 loading(when we see spider for the first time). The lightning still appear but i have no more direction control on it, i can on/off the light normally. If i reload an older save the flashlight is ok, is there something i can do without reloading the old save?

**Comment by skully213** [comment]
Hello, the flashlight just disapeared suddenly right before Labos sector 3 loading(when we see spider for the first time). The lightning still appear but i have no more direction control on it, i can on/off the light normally. If i reload an older save the flashlight is ok, is there something i can do without reloading the old save?

**Comment by KozGit** [comment]
You can move the flashlight between your hand, body, and head. Most likely, the flashlight has been for some reason been moved to your body or your head.  Move you flashlight hand to your chest and click the grip button, and if that doesn't work, move your hand to the top of your head and click the grip button to see if you can grab the flashlight again.

**Comment by skully213** [comment]
That worked! Thx!

**Comment by KozGit** [comment]
Glad it's working!
