### ISSUE TITLE
"copy failed" messages during install - Game will not launch

### ISSUE THREAD

**Issue by Nate-in-AK** [KozGit/DOOM-3-BFG-VR#269]
Install completes without additional error messages, and claims successful install.  The "copy failed" messages scroll by quickly during the install.

When I run "Doom 3 BFG VR Fully Possessed" (with Steam closed)  my PC launches the MR portal, Steam VR, and the a window titled Doom 3 BFG VR Fully Possessed opens for a few seconds, and the contents of the window are 100% grey.

I tried deleting Doom 3 completely and re-downloading from Steam, then re-running installer, but got the same result.   Sadness overtakes me.  

Edit:  Also tried installing via ZIP file.  No file copy errors, but still fails to launch.

**Comment by KozGit** [comment]
What headset are you using?  Try to start with logging enabled and let me know the results:

Here is how to enable logging when starting the game:

Create a shortcut to Doom3BFGVR.exe
Right click on the shortcut, go to properties.
In the target field, add +set logFile 2 to the end - be sure to leave a space after .exe and before +set
Click apply, then ok.
Double click shortcut to launch the game.

Try to start the game. The log file will be stored in c:\users(your user name)\saved games\id software\doom 3 bfg\base\qconsole.log

If you can put the log someplace like pastebin I'll take a look. 

Thanks

**Comment by KozGit** [comment]
Closing issue - no response, or further updates, and I'm unable to find any duplicate issues. Please re-open if you've been unable to resolve.
