### ISSUE TITLE
Shotgun disappearing

### ISSUE THREAD

**Issue by matt90410** [KozGit/DOOM-3-BFG-VR#276]
I am experiencing a strange issue where my shotgun will disappear from my list of weapons.  The game will load with it there, but the moment I change to another weapon (switching using my Oculus Touch controller) and then back again it is gone.

Is there anything I can do to prevent it from disappearing?

**Comment by CarlKenner** [comment]
Is it in your holster on your hip?
What version of this mod are you using?
Do you mean the normal shotgun or the double-barrel shotgun in the expansion?

**Comment by matt90410** [comment]
Thank you!  Yes it was in my holster.  I didn't realise I had one!
