### ISSUE TITLE
Adjust joystick Deadzone?

### ISSUE THREAD

**Issue by Violins77** [KozGit/DOOM-3-BFG-VR#286]
Hi, this is not really an issue with the code, it's just that I thought it'd be the best place to ask. I'm using Fish_Biter fork for WMR, and I got a calibration issue from my left motion controller where it is always drifting to the right. Does anyone know of the console command to adjust the deadzone of the joystick? Please note that it is not the same as the track pad, which is set vr_padDeadzone ".25".

Thank you!

**Comment by CarlKenner** [comment]
vr_jsDeadzone
