### ISSUE TITLE
Recoil is waaaaay too big.

### ISSUE THREAD

**Issue by Nordomus** [KozGit/DOOM-3-BFG-VR#297]
I don't remember this problem with other VR mod. Pistol has recoil like 10x desert eagle. We are playing soldier character, Doomguy ffs and he hold's pistol like 3 year old girl. Any way to adjust this?

**Comment by KozGit** [comment]
FWIW, I don't really consider this a problem. This mod didn't change the fire or reload anims from the original game - the weapon fire rates and recoil were kept true to the original to maintain weapon balance .  The other mod didn't apply movement from the fire/recoil/reload anims at all.
