### ISSUE TITLE
No display in Pimax(5K+)

### ISSUE THREAD

**Issue by g-coded** [KozGit/DOOM-3-BFG-VR#300]
This shows on monitor, but only shows a loading screen in the headset, other(Pimax)users are getting the same result.  I think I tried this with my Pimax when I received it, so it could be a SteamVR update that caused this?

**Comment by Midnightmaster** [comment]
Try the SteamVR Beta:
https://www.windowscentral.com/how-enroll-steamvr-beta
Or a rollback to old version:
https://steamcommunity.com/sharedfiles/filedetails/?id=1086279994

**Comment by g-coded** [comment]
I did try the beta/stable, I don't want to revert to an older version, but I could test it to see if that works.

Also wanted to note, there is a "Move to playing position/ face forward" message on the starting screen which I've never seen on the Vive.  I figured I'd try "Reset View"(voice command) but this didn't work, I confirmed mic/voice commands were working correctly using "Pistol/Shotgun" in game.

**Comment by KozGit** [comment]
How long is the backorder on the Pimax 5k these days?

**Comment by g-coded** [comment]
@KozGit I was a KS backer, store shows in stock(?)

**Comment by KozGit** [comment]
Well, looks like I'll take a look at this issue sometime around may 15th :)

**Comment by g-coded** [comment]
@KozGit - I could have sent you some log files :) ... and Pimax just released a new beta which has "Vive only Compatible Game Mode", but it wasn't that option that fixed it(unless enabling it once worked?).  It does need 'Parallel Projections' enabled to run(which drops performance significantly), I'm not sure if this is game engine related though.

**Comment by KozGit** [comment]
I've been wanting a Pimax for a while, I've just been waffling between lcd/oled.  Finally made up my mind. :)

Will need to make some changes to really support non parallel projections.

**Comment by g-coded** [comment]
@KozGit - What did you choose?  It seems like most new/upcoming hmds are going with lcd.  The new brightness/contrast settings help a lot with the Pimax 5K+(I also lowered Doom's in game setting).

**Comment by KozGit** [comment]
I went with LCD.  I like the color of oled, but I'm not a fan of pentile screen door.  It didn't hurt that the LCD was cheaper too :) ( though I'm tempted to buy the oled model as well and then sell whichever one I like less. )
What's your impression of the Pimax so far?

**Comment by g-coded** [comment]
The FOV is a game changer.  I have been watching these new hmd releases with interest, and when I see the same @105* I immediately stop reading.  The software needs some work(but is improving), and some users(myself included)have trouble getting it to 'fit' right.  There are some hardware defects, support is ok(depending on who/when you ask).  As I said the brightness/contrast control made the lcd panels much better.

**Comment by KozGit** [comment]
Just an FYI, I was able to implement initial support for canted displays without too much difficulty.  Made a pretty big improvement in performance as well as visual quality.  Will definitely be in the next release, whenever that is :)

**Comment by g-coded** [comment]
That's awesome!  I expected a performance bump, but not an increase in vq.
