### ISSUE TITLE
Body moving out of sync.

### ISSUE THREAD

**Issue by wslysnps** [KozGit/DOOM-3-BFG-VR#320]
I've been trying to play this game with smooth locomotion, but as i move around, only mr. doom guy moves, and my head is staying in place, until i stop moving, after which i am teleported to the position of my playermodel. Is there any known solution for this? 

Also, i am playing on a Rift S

**Comment by BrziJoe** [comment]
Go to settings and disable all help against vr sickness. It is a beautifull game and mod, just set it to yourself. 
I do not like defoult..

**Comment by wslysnps** [comment]
Thank you! I got it to work by tweaking the comfort settings. It really is glorious! I remember my mate and i were scared shitless playing it back in 2004 when it came out. This is both great nostalgia and a whole new world.

**Comment by KozGit** [comment]
Glad you got it sorted!
