### ISSUE TITLE
Doesn't Launch

### ISSUE THREAD

**Issue by ThaCheezus** [KozGit/DOOM-3-BFG-VR#327]
[qconsole.log](https://github.com/KozGit/DOOM-3-BFG-VR/files/4260088/qconsole.log)
Installed and doesn't launch. Window opens up and is grey, goes to (not responding) and I have to close the process to close the window. Game runs fine in flat but the mod doesn't work at all. I put the log and it seems it can't load a bunch of files but I don't know why. It's vanilla BFG fresh install with the mod fully posessed.

**Comment by KozGit** [comment]
Did it work without the hi-def texture pack installed?

**Comment by ThaCheezus** [comment]
I don't have a texture pack installed though. I reinstalled a fresh copy to put the mod on.

**Comment by KozGit** [comment]
Thats interesting - there are references to 'phrozo' in your qconsole log - those would only be there if one of the hi-def mods was installed, or had been at some point. 

examples from your qconsole:

loading 'materials/phrozo2_lights.mtr'
...loading 'materials/phrozo2_particles.mtr'
...loading 'materials/phrozo_bfg.mtr'
...loading 'materials/phrozo_chaingun.mtr'
...loading 'materials/phrozo_decals.mtr'
...loading 'materials/phrozo_id_particles.mtr'
...loading 'materials/phrozo_lights.mtr'
WARNING: file materials/phrozo_lights.mtr, line 12: material 'lights/phrozo/biground1' previously defined at materials/phrozo2_lights.mtr:79
...loading 'materials/phrozo_particles.mtr'
WARNING: file materials/phrozo_particles.mtr, line 32: material 'textures/particles/phrozo/bfgblast2' previously defined at materials/phrozo2_particles.mtr:110
...loading 'materials/phrozo_particles_anim.mtr'
...loading 'materials/phrozo_xp.mtr'
...loading 'materials/phtozo2_plasmagun.mtr'

Is it possible you had a hi def pack installed at some point and there are remnants left?  This would definitely cause issues.  

Might not be a bad idea to delete the entire directory, and do a clean install, or do a clean install to a completely new directory.  Are you using the steam version?

**Comment by ThaCheezus** [comment]
I don't have any texture packs though...like at all. I barely got the game yesterday to play it...I already fully deleted the folder too and reinstalled everything multiple times. I'm stumped. I may just refund the game since I just got it for VR.

**Comment by ThaCheezus** [comment]
Yet another install fresh in a new hard drive even and still same shit.
[qconsole.log](https://github.com/KozGit/DOOM-3-BFG-VR/files/4263814/qconsole.log)

**Comment by KozGit** [comment]
Can you give some more info?  Which headset, which version of BFG ( steam, GOG, disc, etc ), and let me know exactly how you are installing the mod?  ( Which mod file you downloaded and how you installed it? e.g if zip file the name, where you downloaded and where you extracted it?)  Also, if you could dump the BFG directory structure to a file it could help too - something is odd here, the phrozo.mtr files listed in the log should not be a part of a clean install, and they're not included in the files for this mod.

**Comment by KozGit** [comment]
Looks like the prozo files were not in the more recent log.  One other thing to try is delete ( backup first ) your save game directory - should be something like 'Users\cheez\Saved Games\id Software\'

(Edit - the config files are stored in the save game directory, deleting will ensure the mod is reset to the mod defaults )

**Comment by ThaCheezus** [comment]
it's off steam, just got the .exe off your github. nothing extra going on. using an htc vive

**Comment by ThaCheezus** [comment]
okay deleting the config was the solution. I looked at the VERY initial file I downloaded and it seems it wasn't a fully possesed vanilla. It was recompiled (I didn't notice) after reinstalling from the gitub(I grabbed it since this morning after giving up last night with the original file I grabbed) So I guess what happened was the config was referencing the messed up files and it kept doing so because I deleted everything EXCEPT the saves folder. I just deleted the whole thing since I don't have any save progress in BFG anyway.

**Comment by ThaCheezus** [comment]
Solution, even if you get linked a github file, just go straight to the website yourself! nothing on your end, this was user error. MB

**Comment by KozGit** [comment]
Awesome, glad it's working! Sorry you had difficulties.  There are a lot of config options, if you haven't yet, take a look at the readme or at some of the YouTube vids on configuring, facepalm made a really good one.

**Comment by KozGit** [comment]
If the mod file you downloaded that didn't work was from NPi2Loup, that's a patch with some updates in it that has to be installed on top of the regular mod.
