### ISSUE TITLE
The game stops responding after the first cutscene

### ISSUE THREAD

**Issue by jekyllgrim** [KozGit/DOOM-3-BFG-VR#329]
The game stops responding after the first cutscene. Also there are two screens displaying the game, one in front of each other.

Anything I can do to help troubleshoot the issue?

**Comment by NPi2Loup** [comment]
Could you send more informations :
- which cutscene? which campaign standard Doom3, RoE or another ?
- which version of Doom3BfgVr did you use ?
- which HDM did you use ?
- did you use some hd textures addon ?
- it crash or hang out ?
- activate log, and send us the log
- if you have a crash dump, could you send it ?

**Comment by jekyllgrim** [comment]
Hey, sorry for not making it a bit more informative :)

I'm using Rift S a,d running version 0.021 Alpha, no mods. Somehow it started working for me for no obvious reason (although I swear it looks like it started working when I enabled logging...) I guess this can be closed no.
