### ISSUE TITLE
Unable to modify/delete VR executable

### ISSUE THREAD

**Issue by swoocemeister** [KozGit/DOOM-3-BFG-VR#330]
Hi,

I tried out your mod and it didn't seem to work with my HMD Odyssey headset. I eventually found a workaround by another user on github (https://github.com/Fishbiter/DOOM-3-BFG-VR/releases/tag/V0.021-Alpha-WMR) that seemed to work for others, so I tried to apply it. However, the .exe included with the latest alpha release does not allow me to modify it at all, so I can't even get it off of my system via cmd prompt or anything. It keeps telling me I require administrative privileges even though I am on an administrator account. I have tried changing the permissions on the file itself but access is denied to me whenever I attempt to change the file's security permissions.
I'm sorry if the answer is really obvious, but I'm at a complete loss here and don't really know how to fix this and would appreciate any assistance.

**Comment by NPi2Loup** [comment]
I really think the exe juste put the files at the right place.
You really should override your files, it may stay a lock. 
You should try to reboot your computer.

I have done an new version with some pending works of original author. 
It include Fishbiter's corrections.
I have try this version with HMD Odyssey, and it works fine, you could try it : 
https://github.com/NPi2Loup/DOOM-3-BFG-VR/releases

**Comment by swoocemeister** [comment]
Thank you for the suggestion! However, I managed to remove the file via Safe Mode, (I recently figured out how to access Safe Mode on Windows 10 haha) so I will be closing the issue. 

Cheers!
