### ISSUE TITLE
Cannot Run Installer

### ISSUE THREAD

**Issue by NixEclips** [KozGit/DOOM-3-BFG-VR#331]
Hey there. I have Doom 3 installed.
After extracting the VR file I saw the installer as an .NSI file. 
So I tried using NSIS to run it but there was an error. 
Then I tried Eclipse IDE from Oracle. 
It only opens the txt file. 
The installer now is an NSIS Script File.
Can you please advise?
Thank you.

**Comment by NPi2Loup** [comment]
Eclipse IDE, shouldn't help here.
If you want to try some coding, use Visual Studio.

In my case installer works fine, but you could put your files manually, it's easy.
You just need to download the mod as a zip and unzip it into your doom3 folder.
Then run the Doom3BFGVR.exe

**Comment by NixEclips** [comment]
> 
> 
> Eclipse IDE, shouldn't help here.
> If you want to try some coding, use Visual Studio.
> 
> In my case installer works fine, but you could put your files manually, it's easy.
> You just need to download the mod as a zip and unzip it into your doom3 folder.
> Then run the Doom3BFGVR.exe

That must be the problem. I didn't unzip into the Doom 3 folder. 
Thank you so much for your reply!

**Comment by NixEclips** [comment]
I unzipped it directly into my BFG folder so I have another folder inside that one called DOOM-3-BFG-VR-master and the installer in there still shows up as a .nsi file that does not run. I removed Eclipse and all the java stuff from previously, as well.

**Comment by NPi2Loup** [comment]
You could remove this DOOM-3-BFG-VR-master folder, it's a copy of source code. You may have click on "clone".
You must take the release : https://github.com/KozGit/DOOM-3-BFG-VR/releases
Or a newer version I have assembled (https://github.com/NPi2Loup/DOOM-3-BFG-VR/releases)

In this zip, there is some dll, a folder Fully Possessed with data and Doom3BFGVR.exe

**Comment by NixEclips** [comment]
I am so sorry to keep bothering you. I was able to extract yours and run the application, thank you. However, I get this error:
 "Couldn't load default.cfg"
Current search path:
C:\Users\nixec\Saved Games\id Software\DOOM 3 BFG/Fully Possessed
C:\Games\Doom 3 BFG Edition\Doom3BFGVR_Fully_Possessed_Alpha021g/Fully Possessed
C:\Users\nixec\Saved Games\id Software\DOOM 3 BFG/base
C:\Games\Doom 3 BFG Edition\Doom3BFGVR_Fully_Possessed_Alpha021g/base
file system initialized.
--------------------------------------
Unknown command 'vid_restart'
Couldn't load default.cfg
Shutting down OpenGL subsystem
...wglMakeCurrent( NULL, NULL ): failed

**Comment by NPi2Loup** [comment]
It's strange because I didn't found any default.cfg.
C:\User\... should be the savegame path, not the install path.
You may unzip the mod release in your steam directory, something like d:\Steam\steamapps\common\DOOM 3 BFG Edition\

**Comment by NixEclips** [comment]
Here I am again, sorry, but I think we're getting close. 
Now it opens a grey screen and then I get the message below. I manually selected an input device, as well, in SteamVR settings. Thank you! (ETA: not sure why that part is bolded)
(ETA2: I’m going to try setting up speech recognition on the PC tomorrow?)

HMDResetTrackingOriginOffset called
 Resetting tracking yaw offset.
 Yaw = -165.832962 old offset = -165.832962 New Tracking yaw offset -165.832962
New Yaw offset = -165.832962
--------- Game Map Shutdown ----------
--------------------------------------
********************
ERROR: Error initializing voice commands.
Unable to load '/dict/voice.dict'
********************
Error during initialization
Shutting down OpenGL subsystem
...wglMakeCurrent( NULL, NULL ): success
...deleting GL context: success
...releasing DC: success
...destroying window
...restoring hardware gamma: success

**Comment by NPi2Loup** [comment]
Could you search in your game repository, where `voice.dict` is ?
It should be at "d:\Steam\steamapps\common\DOOM 3 BFG Edition\Fully Possessed\dict\voice.dict"

**Comment by NixEclips** [comment]
It’s there but the actual path is "c:\Steam\steamapps\common\DOOM 3 BFG Edition\Doom3BFGVR_Fully_Possessed_Alpha021g\Fully Possessed\dict\voice.dict"

Edit: I removed that Doom3BFGVR_Fully_Possessed_Alpha021g folder and pasted the contents in the Doom 3 folder. The game ran in my headset! And then crashed after the opening voice over introduction.

**Comment by NPi2Loup** [comment]
did you put all files from Doom3BFGVR_Fully_Possessed_Alpha021g.zip into your c:\Steam\steamapps\common\DOOM 3 BFG Edition\ folder ?
I may have 13 .dll files and one Doom3BFGVR.exe, correct ?

**Comment by NixEclips** [comment]
Yes, there are 13 .dll and the application. 


https://ibb.co/TWpPXRc

**Comment by NPi2Loup** [comment]
What is your hmd ?
Did you have some error log ?

**Comment by NixEclips** [comment]
Sorry, I have not been able to continue troubleshooting. Will try again when I am able! Thanks for your help.

**Comment by KozGit** [comment]
Reading this - did you ever download the installer.exe or the .zip from the releases page of the repository?  It looks like you downloaded the source or cloned the repository initially - if you don't have this working yet, I would remove everything you've downloaded, delete your bfg directory and do a clean install from steam, then download the installer.exe from the 'releases' section of the repository ( link: https://github.com/KozGit/DOOM-3-BFG-VR/releases/download/V0.021-Alpha/Doom3BFGVR_Fully_Possessed_Alpha021.exe ) and run that .exe   

I'm going to close this issue, as it appears to be install related and there hasn't been an update in a while - if you're still stuck you can open a new issue.  Thx.
