### ISSUE TITLE
RiftCat - Doom 3 BFG VR Bugs

### ISSUE THREAD

**Issue by mbr2xgd** [KozGit/DOOM-3-BFG-VR#332]
I have The Riftcat(Fake VR) is a little different. Please visit: https://riftcat.com/vridge

Can I play Doom 3 BFG VR with RiftCat? 
There is no problem with other games using Riftcat, keyboard and mouse. 

It's complicated to play Doom 3 BFG VR with RiftCat
Here my bugs: 
https://i.imgur.com/N8cyLm3.jpg / https://i.imgur.com/zxMNgid.jpg
https://i.imgur.com/GL1dVOq.jpg / https://i.imgur.com/EmMjZyl.jpg
Doom 3 BFG VR  with RiftCat video: https://youtu.be/qLuV0d85Y6w 

Dcs-world and other there is no bug.
https://i.imgur.com/DOcTngx.jpg / https://i.imgur.com/Gz3KDIb.jpg
Alien: isolation:  https://youtu.be/JMaa6kftMS8
Hellblade: https://youtu.be/YbvEIWCnn9o
Serious Sam VR last hope: https://youtu.be/snT3FUQ49q4

**Comment by NPi2Loup** [comment]
It really seem to be a motion controller bugs. By default Doom3VR support motion controllers to move player's hands, with RiftCat motions controllers are emulated and send incorrect positions.
You may try to change settings (in game settings) and desactivate motion controllers, it should works.
(Doom3VR is playeable with mouse and keyboard this way)

**Comment by mbr2xgd** [comment]
I fixed it. The configuration Is very complicated. 
I can play Doom 3 BFG VR now: https://youtu.be/j8KN-i-96CM
Thank you!

**Comment by NPi2Loup** [comment]
Great :)
Could explain what configuration is needed ? for futur Riftcat users ?

**Comment by mbr2xgd** [comment]
Yes.

Xbox One->Settings(Left, Right): https://i.imgur.com/f6TpcK5.jpg / https://i.imgur.com/12lYsge.jpg
I need to press Y to activate the 1st person view mode. 

[d3bfgvr_controls.txt](https://github.com/KozGit/DOOM-3-BFG-VR/files/4736402/d3bfgvr_controls.txt)

Doom 3BFG VR: Options->Settings->VR OPTIONS->CONTROLS OPTIONS
1 -> https://i.imgur.com/sdkWq2n.jpg = VR COMFORT->SAFETY
2 -> https://i.imgur.com/q9evixt.jpg = VR CONTROL OPTIONS

CONTROL OPTIONS->KEY BINDINGS
1-> https://i.imgur.com/toFsZ2S.jpg
2 -> https://i.imgur.com/v0EXO99.jpg
3 -> https://i.imgur.com/fpGbKwk.jpg
4 -> https://i.imgur.com/mmv8k6R.jpg
5 -> https://i.imgur.com/mmv8k6R.jpg
6 -> https://i.imgur.com/8scbV3x.jpg

Doom 3 BFG VR configuration: https://youtu.be/ig3INosCPKo

There is a tutorial to explain how to use Xbox: https://support.riftcat.com/hc/en-us/articles/360001951280-How-to-use-keyboard-mouse-and-Xbox-controller-integrations

Smartphone Controls: https://www.youtube.com/watch?v=wPXrtjjX-fQ
VR Controls: https://www.youtube.com/watch?v=Kq629e_Gnew

**Comment by mbr2xgd** [comment]
VR Comfort + Safety

<Right Hand>				Teleport
Blink					Teleport mode
Real life				Turning
0					Walk speed adj
None					Motion Sickness Aid
Enabled				KnockBack & Head Stick
Enabled				Step Smooth & Jump Bounce
############			Shake Amplitude

VR Control Options

Motion Controllers			Controller type
Left Hand = Forward			Move Mode
<Full Motion crouching>		Crouch Mode
7					Crouch Trig Dist
10					Weapon Pitch
0					Flashlight Pitch
Voice, No Cursor			Talk Mode
Disabled				Voice Commands

Key Bindings  	

Actions				Key Designment

CONTROLS - MOVEMENT
Forward				W
Backward				S
Move Left				A
Move Right				D
Jump					SPACE
Crouch					C
Turn Left				JOY8
Turn Right				
Click Move
Sprint					LSHIFT
Reset HMD orietation		;,SAY_RESET_VIEW
Confort Turn left			Q
Confort Turn right			E
Teleport				X

CONTROLS - ATTACK/LOOK
Attack					LCTRL,MOUSE1
Flashlight				F,SAY_FLASHLIGHT
Next weapon				MWHEELUP
Prev. weapon				MWHEELDOWN
Reload					R, SAY_RELOAD
PDA/Scroeboard			TAB, SAY_PDA
System Menu(ESC)			SAY_PAUSE, SAY_RESUME, S...
Toggle Lasersight			B
Toggle HUD				H
Next Flashlight Mode			V
Toggle HEading Beam		N
Walk in place
Talk					TALK
Use					T
Look Up				PGDN
Look Down				DEL

CONTROLS - WEAPONS
[d3bfgvr_controls.txt](https://github.com/KozGit/DOOM-3-BFG-VR/files/4736397/d3bfgvr_controls.txt)

Melee/Grabber				1
Fists					SAY_FIST
Chainsaw				SAY_CHAINSAW
Grabber				SAY_GRABBER
Pistol					2, SAY_PISTOL
Shotgun/Obj				3
Single Shotgun			4, SAY_SHOTGUN
Double Shotgun			5, SAY_SUPER_SHOTGUN
Machinegun				6, SAY_MACHINE_GUN
Chaingun				7, SAY_CHAIN_GUN
Grenade				G, SAY_GRENADES
Plasmgun				8, SAY_PLASMA_GUN
Rockets				9, SAY_ROCKET_LAUNCHER		
BFG					0, SAY_BFG
Soulcube/Artifact			Z, SAY_SOUL_CUBE, SAY_ART...

CONTROLS - OTHER
Quick Save				F5
Quick Load				F9
Screeshot				       F12
Chat					
Team Chat
