### ISSUE TITLE
Upside down backwards

### ISSUE THREAD

**Issue by sewerratuk** [KozGit/DOOM-3-BFG-VR#334]
Weird thing, the title menu is fine but as some as I am in the game I'm upside down and backwards. If I go into third person view you can see the arms sticking out the back to the avatar body and the head pointing backwards. Pull stick backwards to go forwards.
Using Oculus Rift S

Any thoughts?

Edit
OK, so it seems that it was the game save from playing in pancake that was screwing it up. Started a new game and it all works fine

**Comment by sewerratuk** [comment]
OK, so it seems that it was the game save from playing in pancake that was screwing it up. Started a new game and it all works fine

**Comment by KozGit** [comment]
Thanks for the update - will close this issue - please re-open if you have any more issues.

Thanks.
