### ISSUE TITLE
Unable to progress past the end of ROE's first level

### ISSUE THREAD

**Issue by foxhound525** [KozGit/DOOM-3-BFG-VR#335]
Hi there - first of all, great work! I completed DOOM3 using RB Doom3 as I couldn't get this to work, but after doing a fresh install for ROE I managed to play the first level. That is unfortunately where the fun ends.

So I get to the lift, press the exit level button, and then the game crashes. Reliably, every single time. A tiny part of the screen stays visible, like a corner of your FOV when you pressed the button, but you can then see the steam VR virtual environment lines around it, and some weird red blue and green dotted lines. Then you get the expected crash. I just can't figure it out because it all works fine up to that point.

Installed using the .exe. The only unusual thing I did was that I cloned the original DOOM3 directory with RBDOOM3 already there and made a copy of it to put somewhere else, then added Fully possessed to that version. If this didn't work I didn't want to screw up RBDOOM3 as I knew that worked fine.

Current Win 10
Current steam build of DOOM 3 BFG
AMD FX-8370 4ghz
GTX1060
16GB RAM (2x8GB)
HTC Vive

**Comment by NPi2Loup** [comment]
First of all, check this new version of the mod : 
It merge the pending work of KozGit and Carl and fix some other bugs, it might fix your issue.
https://github.com/NPi2Loup/DOOM-3-BFG-VR/releases

This mod work with a new .exe, build from this repository source, I can't see how it could use RBDOOM3 code. 
The RBDOOM3 ressources (files, maps, textures, etc...) might be compatible with DOOM-3-BFG-VR.

The crash you decribed looks like a map loading issue, cinematic issue, or a savegame issue, and I know these features are heavly modified by DOOM-3-BFG-VR.

You should try with a fresh build and this mod only, it's already very fun :)

**Comment by foxhound525** [comment]
> 
> 
> First of all, check this new version of the mod :
> It merge the pending work of KozGit and Carl and fix some other bugs, it might fix your issue.
> https://github.com/NPi2Loup/DOOM-3-BFG-VR/releases
> 
> This mod work with a new .exe, build from this repository source, I can't see how it could use RBDOOM3 code.
> The RBDOOM3 ressources (files, maps, textures, etc...) might be compatible with DOOM-3-BFG-VR.
> 
> The crash you decribed looks like a map loading issue, cinematic issue, or a savegame issue, and I know these features are heavly modified by DOOM-3-BFG-VR.
> 
> You should try with a fresh build and this mod only, it's already very fun :)

Thanks, I'll give it a try. I'm doing a fresh install of D3 BFG so hopefully this fixes it! I'll report back once I've finished the first level (assuming this works at all)

**Comment by foxhound525** [comment]
Well I tried 0.21g, doesn't work. The game crashed on startup.
This is the dialogue that comes up before it 'destroys' the window

Error initializing voice commands.
Unable to load '/dict/voice.dict'

Edit: I somehow didn't copy the actual fully possessed folder over, oops. Trying again now

**Comment by foxhound525** [comment]
So after doing a fresh install, and starting a new game, it crashes as soon as the opening cutscene ends. Well it hangs for a very long time, then crashes. Any ideas?

**Comment by NPi2Loup** [comment]
You may activate the logs.
Create a shortcut and edit target to add ` +set logFile 2` to the command line 
It should look like this : `"D:\Steam\steamapps\common\DOOM 3 BFG Edition\Doom3BFGVR.exe" +set logFile 2`

The logs are write there  : `c:\Users\{userName}\Saved Games\id Software\DOOM 3 BFG\base\`

Which HMD did you have ?
All drivers are up to date ?

**Comment by foxhound525** [comment]
So here's the log, I just tried to run a new game. Weirdly it brought up an in-game console in blue when it failed to get past the opening cinematic (the bit with the text and a very pixellated image of mars). I'm using a HTC Vive (original) with vive wands and base stations 1.0. All drivers are up to date.

[qconsole.log](https://github.com/KozGit/DOOM-3-BFG-VR/files/4592840/qconsole.log)

Edit: the only way I've ever got this mod to actually load into a level was by installing using the exe for fully posessed, rather than dragging and dropping. Even then that crashed when you try to finish the level.

**Comment by NPi2Loup** [comment]
The log say there is a incompatibility between animation's files of rocketlauncher_vr.
Are you sure it a pure fresh install ?
You may delete (or rename) your Doom3BFG folder in steam, maybe some files have been kept.

For the install .exe, I don't really know what it do ;) And I don't know how to rebuild it :(

Maybe, if @KozGit is around here, he could help

**Comment by foxhound525** [comment]
I'm pretty sure it was clean, but I will do a fresh install one more time just to be certain.

**Comment by KozGit** [comment]
Hey - on line 1853 of the log, I see the following error:

ERROR: Model 'models/md5/weapons/rocketlauncher_view/viewrocketlauncher_vr.md5mesh''s joint names don't match anim 'models/md5/weapons/rocketlauncher_view/viewrocketlauncher_vr_idle.md5anim''s

It looks like there may be an issue with the install - may want start with a completely clean D3BFG install, then run the Fully Possessed installer, or if using the .zip, unzip into your game directory. The readme in the zip or on the main page of the git repo should have all the instructions you need. Hope this helps!

**Comment by foxhound525** [comment]
Well I did another install yesterday, same problem.

Here's specifically what I did;
- Delete the Doom 3 BFG install directory folder
- Verify integrity of game files with steam (547 files reaquired)
- Open Doom3BFGVR_Fully_Possessed_Alpha021g.zip, copy all of its contents to X:\Additional Games\steamapps\common\DOOM 3 BFG Edition (where my install is) and overwrite everything when it asks.
- Add Doom3BFGVR.exe to steam as a non-steam game, tick include in VR library.
- Run SteamVR, search for and run Doom3BFGVR.exe
- Start new game, watch text dump at beginning of new game, stare at the blurry image of mars for 10 minutes hoping the game will get past the crash and actually start the in-engine cutscene where a marine talks to Mcneil.
- Game not responding, exit the game.

As you can tell, it still isn't working.

I'll try and properly uninstall it this time, delete my save game folders too, if it doesn't work after this then the problem can't be on my end.

Edit: after doing the above, I'm able to load into the game now, so now I need to see if I can actually load into the second level after completing the first, as thats the furthest I've ever got. I will post back here shortly after that.

**Comment by foxhound525** [comment]
That actually worked, managed to get to level 2 without issues and the performance seems to be better than before too. Thanks for the help, I have properly uninstalled it before and reinstalled and that didn't work then but it seems to be ok now. 

My final question, are any hd texture packs compatible with this?

**Comment by NPi2Loup** [comment]
Good to hear that.
Your issue may come from savegames.. or config..

For HD texture pack, I don't know, everything that change 3d models probably doesn't work.
But mods that change only textures should work.
