### ISSUE TITLE
Compile new version!

### ISSUE THREAD

**Issue by Bluscream** [KozGit/DOOM-3-BFG-VR#336]
https://github.com/KozGit/DOOM-3-BFG-VR/compare/V0.021-Alpha...master

**Comment by NPi2Loup** [comment]
This is almost done here : https://github.com/NPi2Loup/DOOM-3-BFG-VR
A lots of Carl's and Koz's work are rebundle here, but dual weilding which I can't make it work good.

**Comment by KozGit** [comment]
I am currently working on a pretty major revision - no ETA at this time but it is in active development.  There will not be another update until the revision is complete.
