### ISSUE TITLE
Proper Oculus Touch bindings

### ISSUE THREAD

**Issue by Bluscream** [KozGit/DOOM-3-BFG-VR#337]
I wish to not relearn everything but use familiar controls like A=Jump. Does someone have proper bindings that i can import to steamvr? (i am using the new oculus controllers from the quest but it shows the old (legacy ones in steamvr bindings screen as shown below)

![image](https://user-images.githubusercontent.com/3318223/83329191-5e537080-a288-11ea-895f-f5bbc0c2e548.png)

**Comment by NPi2Loup** [comment]
Doom 3 BFG VR  already include a option screen to remap all your binding. 
I think it didn't support steamvr binding.

**Comment by KozGit** [comment]
Yes, you can rebind all controls through the in-game menus - take a look at the readme file, it has pretty detailed descriptions of all options and how to set them.

**Comment by KozGit** [comment]
( Closing issue as this can be addressed through the in game menus )
