### ISSUE TITLE
How to open console in VR?

### ISSUE THREAD

**Issue by Bluscream** [KozGit/DOOM-3-BFG-VR#338]

**Comment by NPi2Loup** [comment]
you could open console with the default key :  ² but it will show in your mirror screen only, not in VR

**Comment by Bluscream** [comment]
²?

**Comment by NPi2Loup** [comment]
The key at the **LEFT** of 1 key and top of tab (I said right, oups)

**Comment by Bluscream** [comment]
The key on the right of 1 is 2 not ² or did you mean 2 in the first place?

**Comment by KozGit** [comment]
You use the tilde key ( ~ ) to open the console. The tilde is above Tab, under Escape, and to the left of ' 1 ' on a standard keyboard.

**Comment by Bluscream** [comment]
I tries tilde, it did not wirkt

**Comment by KozGit** [comment]
are you using the fully possessed mod, or straight D3BFG?  Console access is disabled by default in normal D3BFG. The console can be enabled through the Steam client. Select DOOM 3 BFG Edition in the Steam library, right-click, and select Properties. In the General tab, select Launch Options and enter <+set com_allowconsole 1>. Pressing the tilde key [~] in-game will now open the console.   note - don't press shift while pressing the tilde key.  I suppose it's actually the ' grave' or ' ` ' key on a standard us keyboard.

**Comment by Bluscream** [comment]
ill try and report back
