### ISSUE TITLE
Where is Download?

### ISSUE THREAD

**Issue by Blazkonerd** [KozGit/DOOM-3-BFG-VR#339]
Hello,
I just wanted to download this mod again and I cannot find the link to the downloads page (I am searching the Doom3BFGVR_Fully_Possessed_Alpha021.exe). I remember there was a menu bar where you could click on "releases" iirc. Now that menu bar is totally missing! It is very strange. I made a screenshot of the situation.
Thanks, Daniel

![20200627-213620-001](https://user-images.githubusercontent.com/67520720/85931117-2c9eeb00-b8c2-11ea-9bd0-6d9e4e3e25eb.png)

**Comment by NPi2Loup** [comment]
Releases link is now in the right part of the main screen (look in your screenshot)

**Releases**
**3** tags

**Comment by Blazkonerd** [comment]
> 
> 
> Releases link is now in the right part of the main screen (look in your screenshot)
> 
> **Releases**
> **3** tags

Hi Loup,
Thanks for the answer, I found it out myself shortly before you replied. But I think that is not well designed by GitHub. The word "Releases" is not even recognizable as a link. And who gets the idea to click "3 tags" when trying to download a file? Very insiderish and not visitor friendly. But your mod is awesome :-D
Thanks, Daniel

**Comment by KozGit** [comment]
I have to agree, it's not completely obvious.  I'm going to go to ahead and close this issue since you were able to get to the download. Thanks!
