### ISSUE TITLE
Index controller binding key issue/question

### ISSUE THREAD

**Issue by Crinon** [KozGit/DOOM-3-BFG-VR#352]
Hello,
First, thank you for your work, VR integration is very cool.
I ran into an issue though, with my index controller the game is unplayable:

- left stick is classic move, but it triggers torch for every input detected
- right stick is for teleportation, but it changes my weapon for every input detected

In menu, binding is not possible, si did I made anything wrong ??

**Comment by NPi2Loup** [comment]
Often this issue comes when there is multiple actions bind to the same input.
I don't know why, but with Index Controller, its more often.
You may : 
- try to reset all inputs settings and set them from scratch
- look at this issue : https://github.com/KozGit/DOOM-3-BFG-VR/issues/341

**Comment by Crinon** [comment]
Thank you for your reply, I just rebinded them
