### ISSUE TITLE
Please add option (cvar or similar) to disable gibbing

### ISSUE THREAD

**Issue by AndersMalmgren** [KozGit/DOOM-3-BFG-VR#369]
Gibbing of monsters really takes me out of immersion. And for some reason NPi2Loup build gibs mich easier than the V0.021-Alpha release found here.

**Comment by KozGit** [comment]
This is a standard D3 cvar already. Set g_bloodEffects to 0.

**Comment by AndersMalmgren** [comment]
No it does not work as you think. It disables all blood effects not only gibbing.

**Comment by AndersMalmgren** [comment]
I also think something is up with monster health in latest build. Revenants are killed with one shotgun blast on veteran

**Comment by NPi2Loup** [comment]
With the RV, there's a headshot boost.
With a shotgun, it's easier. 
See change log :
"Added headshot damage multiplier vr_headshotMultiplier (defaults to 2.5x)"

**Comment by AndersMalmgren** [comment]
> With the RV, there's a headshot boost. With a shotgun, it's easier. See change log : "Added headshot damage multiplier vr_headshotMultiplier (defaults to 2.5x)"

Can we disable that? It's way too easy as it is :) plus the gibbing

**Comment by AndersMalmgren** [comment]
Ah it's a cvar? Will test

**Comment by AndersMalmgren** [comment]
Yupp that worked. I can udnerstand its needed for teleport folks. But for us that move with youstick doom 3 is not harder in VR than on desktop. Almost the opposite. Maybe add the cvar also as a menu option?
