### ISSUE TITLE
Upscale hands and weapons when world scale < 1

### ISSUE THREAD

**Issue by AndersMalmgren** [KozGit/DOOM-3-BFG-VR#370]
I'm 175 cm short and the game feels OK scaled (the assets in Doom 3 are a mess scale wise) if i choose crouch to height and world scale at 0.9. But hands and weapon in hand feels too small now. How about counter scale the hands and item in hand like 1/scale and multiply the transform scales against that so if so let scale is 0.9. make hands and weapon scale by 1/0.9

**Comment by KozGit** [comment]
The doom marine does have small hands in D3, it is a little odd.  Scaling individual parts of the player model, or just the weapons is actually a little more complex than it may originally seem, and unfortunately I don't see this being something I would implement at this point, with everything else still to work on.  Thanks for the suggestion though!
