### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by andybak** [KozGit/DOOM-3-BFG-VR#55]
(Sorry - I know this isn't an issue as such but there's no other place to post)

I've been following development with keen interest. The locomotion and speech stuff looks amazing. Do you have a rough idea when you'll release a new build? Even an experimental one would be good for those of us that just want to try out the new features without much expectation of stability or completeness.

**Comment by CarlKenner** [comment]
We're mostly waiting for Samson (KozGit) to finish up the teleport graphics, parabolic teleport aiming, and the new folder structure.
But I should probably generate player AAS (navigation) files for the remaining levels that I haven't done yet. The process is automatic but it takes about an hour for each map.
I'm trying to remember if there's anything else I need to fix.

**Comment by KozGit** [comment]
Sorry for the wait guys.  Teleport aiming beam is implemented - I just need to incorporate the existing pulls and finish integrating it, working on that now.  Once complete, there are two bugs I want to chase down then a new release.

**Comment by KozGit** [comment]
Closing the issue, as it's been released. Yea!
