### ISSUE TITLE
Starting game

### ISSUE THREAD

**Issue by tkapis** [KozGit/DOOM-3-BFG-VR#6]
Hi Samson, the game is working fantastically with the new update for OpenVR. Haven't found any problem yet apart from the start screen where it says face forward and press any key. For some reason it takes a lot of key presses to recognize the press and the length of time varies every time.

**Comment by KozGit** [comment]
Hey, see this issue, working on it now.  The native oculus and openvr code bases are being merged into one executable, will get this sorted once that's tested - ( should finish merge tonight).  I'll update when it's done.

**Comment by KozGit** [comment]
This was fixed in recent releases.
