### ISSUE TITLE
Teleporting rules

### ISSUE THREAD

**Issue by CarlKenner** [KozGit/DOOM-3-BFG-VR#63]
Here's the system I used for teleporting. Let me know if there's anything we should change or make optional:

- Teleporting is instantaneous. Originally, I thought this would break gameplay too much, but after playing with it, I like it that way. Most monsters have ranged attacks and can adjust to your new position faster than you can, so it's not really cheating. You can rush across the retractable bridge in mars city underground before it finishes opening, but you could probably do that by running anyway, and it doesn't matter because the door is locked and you can jump down.
- You can teleport anywhere you could reach from your current position by walking, crouching, jumping onto something, or falling without taking damage... if you can aim at the floor there.
- Any events along the path you would have to take to get there are triggered, including some environmental damage.
- It doesn't check for physics objects or monsters blocking your path, and you never actually go along that path except to check for doors, windows, and triggers.
- You can't teleport across gaps that you have to jump across. That's mostly because the AAS can't handle that kind of reachability. But perhaps it's good, because there's supposed to be an element of skill involved.
- You can't teleport to areas you could reach by climbing ladders. That's not intentional, it's just that the AAS can't handle it.
- There's an option to choose whether or not you can teleport places you can reach by going through a door that is currently closed but not locked.
- There's an option to limit teleport path length/complexity so you can't skip half the map, but currently it's set high enough so you can teleport across the railings and tightrope in Mars City Underground. I had to do that because it won't let you teleport onto the tightrope (probably because of the angle of the model surface).
- You can only teleport places your character can fit. That is handled by the AAS (if there's no player AAS file, you can only teleport places a 48x48 monster could fit.) Currently, it doesn't check whether you need to crouch, unlike Budget Cuts, but Leyland's crawlspace code can handle it. Because of issues with the AAS not recognising many models as solid, and because of some stairs, it's sometimes possible to teleport under some objects you shouldn't be able to. But crawlspace code can handle it.
- There are issues with the AAS not recognising patches and models, so there's some places, eg. rocky ground, you can't teleport onto, like the Mars surface in Mars City Underground (to collect the adrenaline and armour shards).
- Trying to teleport close to (or through) a locked door will trigger the locked door event and any other events at the door location, but actually teleport you a comfortable distance away.
- The AAS doesn't recognise glass windows as solid, so I check the path for them to stop you from teleporting into or through them, even if you stick your hand through the window.
- The AAS doesn't recognise the hangar walls as solid, but the fact that you can't see through them to aim stops you from teleporting through them, unless you stick your hand through the wall. But you can teleport to the edge of the wall where you are standing half inside the wall, which isn't good.
- You can always teleport into a nearby elevator. I had to add that because the AAS doesn't handle elevators well. There's still an issue teleporting OUT of elevators that I haven't fixed yet, but if you teleport or walk to the threshold first, you can teleport out.
- You can't teleport onto a monster or NPC, unless they are dead.
- Some objects (eg. most medium and small crates) aren't recognised as solid in the AAS, and movable physics objects can obviously never be, but I use the aiming code to check the height of the object, and if it's within jumping height of the AAS floor (and the floor isn't sloped) then I allow you to teleport onto it. If the object in the same AAS area as your current position, then I check the height you are aiming at relative to your current feet position, and if you could jump or fall that far, I let you teleport there. That allows you to climb up stacks of crates, but you have to do it one crate at a time.
- If aiming at a floor, your aim cursor will be nudged to a nearby valid location if you try to aim too close to a wall or somewhere you can't go. This sometimes causes you to jump futilely if you aim at a desk or ledge within jump height that you can't go onto (because it's marked player clip), but that's what people would try anyway if there was no teleporting, so it's not really a problem.
- Stairs are at incorrect heights in the AAS file (they're one step above where they should be), but I work around that by using the aim height instead.

If there's no player AAS file, I use the monster AAS file, but that makes it impossible to teleport to many places you should be able to go. If there's no monster AAS file either (only multiplayer maps with no monsters), I let you teleport anywhere you can aim at a floor that's within jump or fall height of your current position. I will generate player AAS files for the multiplayer maps though.

**Comment by KozGit** [comment]
I'm looking at this now while integrating the aiming beam.  I haven't had much time to play with the teleport itself, so will do as soon as I can.

The aiming beam works by setting a velocity for the beam, the distance between points for the initial hit scan, the max number of points to scan thru, and the max distance below your current height the beam will scan to. ( This keeps the arc from growing out of control if aming upwards but the arc comes down in empty space). 
The arc is scanned point to point  'distance' units apart for a gameLocal.clip.TracePoint hit. The hit point is inspected for suitable pitch, and hits to certain materials were ignored if the pitch didn't indicate a floor to eliminate handrails. Finally a clip check is performed to see if a crouched player could fit there, then it queried CanReachPosition to finally arrive at the final endpoint of the arc.  Once the endpoint is determined the beam model is updated to create the arc from the origin to the endpoint with a target at the end which indicated valid teleport space.  I'll need to modify this to support your new CanReachPosition.   

It's not integrated at all yet, so it's essentially broken and unplayable, but you can see the beam in the latest commit, feel free to offer any feedback on size, shape, color, whatever - I'm not much of an artist, Also would like feedback on beam length etc.  You can vary the behavior of the beam with the vr_teleportVel, vr_teleportDist, vr_teleportMaxPoints, and vr_teleportMaxDrop cvars.

Right now the beam can originate from the hand, the flashlight, or the barrel of the weapon.  Was thinking maybe some form of small teleport emitter model might be better on the weapons than using the barrel, any thoughts?

**Comment by CarlKenner** [comment]
We don't have a teleporter. It's a metaphor for walking. So we shouldn't have a teleporter model.

> but you can see the beam in the latest commit

No, I can't. I can't see anything. How do I make your work appear?

**Comment by KozGit** [comment]
Whoops, looks like the updated vr.mtr file didn't make it in the commit, sorry about that.  Try it now.

**Comment by CarlKenner** [comment]
You haven't pushed any changes yet, there's nothing to try.

**Comment by KozGit** [comment]
Tortoisegit got tangled.  Committed locally but push failed, should be resolved now. Argh,

> We don't have a teleporter. It's a metaphor for walking. So we shouldn't have a teleporter model.

But is it a metaphor that would look better emitting from a generic doodad? :) 
The beam just seems odd originating from the flashlight or the weapon barrel, I'm trying to think of ways to make it look better.

**Comment by CarlKenner** [comment]
Wow, that's beautiful! Great work!

The parabola will make climbing stairs easier.

Here's some feedback:

It's perhaps a little bit to intense with the thick outer border, but that might just be because it's on all the time, instead of just when I'm teleporting. But some alpha would fix it.

It's 2D, which is a problem if you're teleporting above your eye height. I think other games also have some sort of cylinder in addition to the ground sprite.

We need a way to indicate invalid teleport destinations. Perhaps if we just adjust the colour channels to only show red when we can't teleport? And I'm not sure what to show if we're aiming at a wall.

I'll have to look at what other games do.

Also, this isn't about your artwork, but other games show the chaperone boundary when you teleport. We could try adding that later if we want.

And I don't know if we should allow rotating when teleporting like The Gallery does.

You're right, it does look a little odd coming from the weapon or flashlight. Perhaps it should come from our hand instead? Or even from our body somehow? I don't know. But it won't be so noticeable if it's only on for the short time while we're teleporting.

Also, in Budget Cuts there's text telling us to duck if we're too tall for the teleport destination. I don't know if we should add something like that, and if so what's the best way.

**Comment by KozGit** [comment]
> Wow, that's beautiful! Great work!
Thanks! 

>It's perhaps a little bit to intense with the thick outer border,
The beam, or the ground target? ( or both?).  I played with this a little bit, the way translucency is handled makes the intensity vary depending how bright/dark the surrounding area is.  It was originally a little dim in dark areas, maybe I overcorrected.

> It's 2D, which is a problem if you're teleporting above your eye height. I think other games also have some sort of cylinder in addition to the ground sprite.

This is probably a good idea.  I was going to add this, but then worried that it would just be too much visually.  I'll play around with it, I don't think it will be too hard.  Maybe I'll try some particle effects and see how it looks.

> We need a way to indicate invalid teleport destinations. Perhaps if we just adjust the colour channels to only show red when we can't teleport? And I'm not sure what to show if we're aiming at a wall.

Right now, the big target circle should disappear if it's not a valid teleport target, leaving just the beam and the smaller center dot where the beam touches the surface - are you thinking the outer circle should always be on and just change color?  

> You're right, it does look a little odd coming from the weapon or flashlight. Perhaps it should come from our hand instead? Or even from our body somehow? I don't know. But it won't be so noticeable if it's only on for the short time while we're teleporting.

Maybe the beam origin can be surrounded by some form of particle field around the hand/flashlight/barrel to some degree?

**Comment by CarlKenner** [comment]
On second thoughts, it's probably OK how it is for invalid targets. 

But I'd like to try moving the big circle to teleportPoint, while the parabola and smaller circle stay at teleportAimPoint.

**Comment by KozGit** [comment]
I updated the telepad a little - added a cylinder to the target per above, changed how the beam originates from the hand/ flashlight/ weapon and added a flare to the origin end of the beam.  I like the way the beam originates now better, but I'm not sure how much I like the particles in the cylinder.  Thoughts?

I really like the code that offers aim assist for finding a better teleport destination, but don't care for the way it looks when the target and beam don't align.  I added an experimental cvar vr_teleportShowAimAssist to change this behavior - if set to 0, teleporting will use the aim assist point but not actually move the target.  This surprisingly seems to work better than I would have thought, although I haven't really tested it exhaustively.

Do you think it would be worthwhile to allow the player to rotate the teleport destination  so they can change the direction they are facing at the same time?  I don't think this would be much trouble to implement, just not sure how much desire there would be for it.

**Comment by CarlKenner** [comment]
Yeah, I really broke your lovely artwork by moving the big circle to the aim assist location. Maybe if we update the last joint of the parabola, it would look better? Or if we could disconnect the bright circle from the centre of the big circle, and keep it at the end of the parabola, then it would look OK with aim assist. But not showing the aim assist position is also a good option.

Eventually, it would be good to be able to rotate the teleport destination, especially if we can draw the new playspace or chaperone boundary at the teleport destination, like in The Gallery. But other games like The Lab work fine without rotation. That's for the Vive though. Oculus would probably want us to be able to rotate the teleport, because many people only have a 180 front-facing tracking setup. And seated players would probably like rotating the teleport.

I'll try out your new artwork now and give you some feedback.

**Comment by CarlKenner** [comment]
I like the new artwork. Especially the beam start.

I'd make the particles in the cylinder more subtle and less white. But I like having the particles.

Your vr_teleportShowAimAssist does work surprisingly well. Well done. I'm happy for that to default to 0.
