### ISSUE TITLE
Saved game folder should be in original folder

### ISSUE THREAD

**Issue by CarlKenner** [KozGit/DOOM-3-BFG-VR#65]
Now that we're using a different "base" folder called "Fully Possessed", the saved game folder doesn't need to be in a separate folder anymore. It would make more sense to have the "Fully Possessed" folder inside the original Doom 3 BFG save game folder ("DOOM 3 BFG") instead of inside "DOOM 3 BFG VR Fully Possessed".

**Comment by KozGit** [comment]
Makes perfect sense, fixed in most recent commit.
