### ISSUE TITLE
Error starting new campaing after finishing previous campaign.

### ISSUE THREAD

**Issue by KozGit** [KozGit/DOOM-3-BFG-VR#83]
After finishing the hell level of RoE, selected new campaign ( ok to overwrite) ->Roe->Marine.

The initial text scroll plays, but the initial cutscene fails to play and the player is stranded in the empty PDA room.

**Comment by CarlKenner** [comment]
Looks like I broke cutscenes in normal games somehow. Sorry.

**Comment by CarlKenner** [comment]
Fixed in pull request.

**Comment by KozGit** [comment]
That was quick - great job, no need to aplogize!
