### ISSUE TITLE
Start menu is black

### ISSUE THREAD

**Issue by ryanbalsdon** [KozGit/DOOM-3-BFG-VR#9]
When I boot this up, all I see is black. Pushing random buttons for a bit, I get the main menu music. Pushing more random buttons eventually boots up the actual game, which works perfectly.

Where are the console logs saved? Maybe there's something failing to load?

**Comment by ryanbalsdon** [comment]
This was using the 0.015 release build on a CV1 through an ATI 390X.

I tried walking all around the space to see if it was a clipping problem but had no luck. It wasn't just the first splash screen that was dark, it was everything up to the loading screen to get into the game. The loading screen was also mirrored in each eye instead of 3D.

Once in the game though, everything was flawless.

**Comment by CarlKenner** [comment]
It could be a shader issue. I think ATI cards are more fussy about shaders than nvidia. But I don't have ATI.

**Comment by ryanbalsdon** [comment]
Makes sense to me. If it was a compile error, where would that log be saved?

**Comment by jasonbdj** [comment]
I have the sane problem but with 290x

**Comment by TrebuhD** [comment]
Same problem with the R9 390.

**Comment by doenerkalle** [comment]
and R9 290x :(

**Comment by ramph** [comment]
Same problem here with the R9 290x.

Base game works, installed "Doom 3 BFG Hi def 2.9 full release" from moddb, installed "Doom 3 BFG VR", ran the game, black screen, then remembered to delete the "Generated" directory in Base folder.

Did anyone ever find a solution to this?

**Comment by noelevatorstudio** [comment]
Same problem with R9 390

**Comment by doenerkalle** [comment]
I could just press right trigger 3 or 4 times and the game started.
I could then access all the options/save and load menus from within the game. 
The problem was, when i saved and started the game again it crashed :(

**Comment by CarlKenner** [comment]
In all John Carmack games, you just have to keep pressing Enter (or in this case, right trigger) until you're in the game.
There seem to be bugs in the saved games, so I don't know if that's the problem with the crashing or if it's related to your black menu issue.

**Comment by KozGit** [comment]
Actually getting an rx480 today for a htpc, so I'll take this one.

**Comment by tigrezapatos** [comment]
RX480 here.  Same issue.

**Comment by KozGit** [comment]
Ive got this sorted out. Testing positional tracking in the menus, will update when done.

**Comment by KozGit** [comment]
Allright, should have this sorted out now. Added basic positional tracking to the menu screens as well. I've attached another test .exe to the bottom of this message, let me know how it works.

[Doom3BFGVR_AMD_Test2.zip](https://github.com/KozGit/DOOM-3-BFG-VR/files/852717/Doom3BFGVR_AMD_Test2.zip)

**Comment by tigrezapatos** [comment]
The game works now!  Is third person teleporting the only way?  I'd much prefer a laser.  Having my guy run out in front of me so I can start dying before I snap to stuff is annoying.  Also frustrating when you need to run or make other fast movements.

**Comment by KozGit** [comment]
Read the readme - there are a variety of movement modes to chose from - you don't have to use third person.
