### ISSUE TITLE
vr_talkWakeMonsters affecting monster spawns

### ISSUE THREAD

**Issue by CarlKenner** [KozGit/DOOM-3-BFG-VR#97]
Important!! 3-3-2017
A setting was inadvertantly left on in this build that affects monster spawns.
You will most likely want to disable this.
From the console ( press ~ to open console ) type:
vr_talkWakeMonsters 0

Then press enter. This will prevent voice commands from waking monsters.

> i think something may be wrong with the update.....some of enemies spawn before you do  the required scripted events that you would normally do....it seems like they all spawn at once..which is actually pretty amusing when i went though a level and was surprised by how many mobs came at me in the administration office withing 5 minutes of starting the level lol. 

> There was a later addition to the mod that I neglected to highlight in the readme, sorry! There are two new cars, vr_talkWakeMonsters and vr_talkWakeMonstetRadius.  If vr_talkWakeMonsters is set to 1 ( which is the default for now) , talking or making noise will wake up all monsters within the vr_talkWakeMonstersRadius. Set to 0 to disable.

**Comment by KozGit** [comment]
Fixed, thanks Carl!
